### ISSUE TITLE
PyTorch Version Checking Issue

### ISSUE THREAD

**Issue by XinDongol** [open-mmlab/mmselfsup#10]
In `openselfsup/models/necks.py`, the version of PyTorch is checked to becomingly support `syncbn`.

```python
        if StrictVersion(torch.__version__) < StrictVersion("1.4.0"):
            self.expand_for_syncbn = True
        else:
            self.expand_for_syncbn = False
```

However, it seems that the `StrictVersion` (from `from distutils.version`) cannot support PyTorch version ids like `1.6.0a0+b0b9e70`. Basically, It will return 
```
ValueError: invalid version number '1.6.0a0+b0b9e70
```

**Comment by XinDongol** [comment]
An alternative is `packaging.version`

```
> from packaging import version
> version.parse("1.6.0a0+b0b9e70") < version.parse("1.4.0")
False

> version.parse("1.3.0a0+b0b9e70") < version.parse("1.4.0")
True
```

**Comment by XiaohangZhan** [comment]
Fixed accordingly. Thank you!

**Comment by XinDongol** [comment]
> Fixed accordingly. Thank you!

Thanks a lot. `OpenSelfSup` is awesome!
