### ISSUE TITLE
checkpoint with necks

### ISSUE THREAD

**Issue by lzyhha** [open-mmlab/mmselfsup#100]
Thanks for your contribution in self-supervised learning. Now I want to train a model with the pretrained model in ImageNet. Could you please release the checkpoint with related necks, such as NonLinearNeckSimCLR in SimCLR?

**Comment by Jiahao000** [comment]
The pre-trained weights for related necks are not available since they are discarded when transferred to downstream tasks. You may pre-train by yourself to obtain the weights.
