### ISSUE TITLE
Different number with MoCo official repo for the linear classification

### ISSUE THREAD

**Issue by deeptimhe** [open-mmlab/mmselfsup#102]
For the **supervised** ImageNet linear classification, the number reported in the Model Zoo is 74.12% (last). While it is 76.5% in MoCo paper: https://arxiv.org/pdf/1911.05722.pdf, and is 76.1% in VISSL: https://github.com/facebookresearch/vissl/blob/master/MODEL_ZOO.md. Obviously there exists a large gap and I wonder what makes such difference?

**Comment by Jiahao000** [comment]
As shown in appendix of the MoCo paper, the 76.5% is reported by fine-tuning all layers end-to-end, while we frozen the backbone following the common protocol. In VISSL, they use the "Multi-head" setting, and 76.1% is the result of feat5. The feat5 number reported in our Model Zoo (76.17%) is comparable with the corresponding layer.

**Comment by deeptimhe** [comment]
@Jiahao000  Thank you for your clearly response! Nice job! BTW, the difference between "feat5" and "last" lies in the former one evaluates on the features before GAP, the the later one evaluates on the features after GAP?

**Comment by XiaohangZhan** [comment]
> @Jiahao000 Thank you for your clearly response! Nice job! BTW, the difference between "feat5" and "last" lies in the former one evaluates on the features before GAP, the the later one evaluates on the features after GAP?

What you mean by `GAP`? Settings "feat"5 and "last" are different in pooling and BN strategies, please check the code.
