### ISSUE TITLE
Hanging on runing VOC07 SVM & SVM Low-shot Benchmark

### ISSUE THREAD

**Issue by opsiff** [open-mmlab/mmselfsup#103]
Hello，thanks for your work.
What should I do to solve this problem?
When I run`bash benchmarks/dist_test_svm_pretrain.sh configs/selfsup/simclr/r50_bs256_ep200.py pretrains/simclr_r50_bs256_ep200-4577e9a6.pth feat5 1  --deterministic`
It is often random hang on like
` /anaconda3/envs/open-mmlab/lib/python3.7/site-packages/scikit_learn-0.24.1-py3.7-linux-x86_64.egg/sklearn/svm/_base.py:986: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
 48%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                           | 182/380 [09:34<16:11,  4.91s/it]`

It works well on`bash benchmarks/dist_test_svm_pretrain.sh selfsup/moco/r50_v2.py pretrains/moco_r50_v2-e3b0c442.pth feat5 1  --deterministic` and`bash benchmarks/dist_test_svm_pretrain.sh selfsup/moco/r50_v1.py pretrains/moco_r50_v1-4ad89b5c.pth feat5 1`

Some Other Information:

- System Version: `Linux version 5.4.0-42-generic (buildd@lgw01-amd64-023) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020`  
- NVIDIA-SMI 460.56       Driver Version: 460.56       CUDA Version: 11.2   
- Conda Packege Version:
   Name                    Version                   Build  Channel
  _libgcc_mutex             0.1                 conda_forge    conda-forge
  _openmp_mutex             4.5                       1_gnu    conda-forge
  absl-py                   0.12.0                   pypi_0    pypi
  addict                    2.4.0                    pypi_0    pypi
  apex                      0.1                      pypi_0    pypi
  blas                      1.0                         mkl  
  bzip2                     1.0.8                h7f98852_4    conda-forge
  ca-certificates           2020.12.5            ha878542_0    conda-forge
  cachetools                4.2.1                    pypi_0    pypi
  certifi                   2020.12.5        py37h89c1867_1    conda-forge
  chardet                   4.0.0                    pypi_0    pypi
  cudatoolkit               11.1.1               h6406543_8    conda-forge
  cycler                    0.10.0                   pypi_0    pypi
  faiss                     1.7.0           py37cuda111hcc9d9d6_8_cuda    conda-forge
  faiss-gpu                 1.6.1                    pypi_0    pypi
  ffmpeg                    4.3                  hf484d3e_0    pytorch
  freetype                  2.10.4               h5ab3b9f_0  
  future                    0.18.2                   pypi_0    pypi
  gmp                       6.2.1                h58526e2_0    conda-forge
  gnutls                    3.6.13               h85f3911_1    conda-forge
  google-auth               1.29.0                   pypi_0    pypi
  google-auth-oauthlib      0.4.4                    pypi_0    pypi
  grpcio                    1.37.0                   pypi_0    pypi
  idna                      2.10                     pypi_0    pypi
  importlib-metadata        4.0.1                    pypi_0    pypi
  intel-openmp              2020.2                      254  
  joblib                    1.0.1                    pypi_0    pypi
  jpeg                      9b                   h024ee3a_2  
  kiwisolver                1.3.1                    pypi_0    pypi
  lame                      3.100             h7f98852_1001    conda-forge
  lcms2                     2.12                 h3be6417_0  
  ld_impl_linux-64          2.33.1               h53a641e_7  
  libblas                   3.9.0           1_h86c2bf4_netlib    conda-forge
  libfaiss                  1.7.0           cuda111hf54f04a_8_cuda    conda-forge
  libfaiss-avx2             1.7.0           cuda111h1234567_8_cuda    conda-forge
  libffi                    3.3                  he6710b0_2  
  libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
  libgfortran-ng            9.3.0               hff62375_19    conda-forge
  libgfortran5              9.3.0               hff62375_19    conda-forge
  libgomp                   9.3.0               h2828fa1_19    conda-forge
  libiconv                  1.16                 h516909a_0    conda-forge
  liblapack                 3.9.0           5_h92ddd45_netlib    conda-forge
  libpng                    1.6.37               hbc83047_0  
  libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
  libtiff                   4.1.0                h2733197_1  
  libuv                     1.41.0               h7f98852_0    conda-forge
  lz4-c                     1.9.3                h2531618_0  
  markdown                  3.3.4                    pypi_0    pypi
  matplotlib                3.4.1                    pypi_0    pypi
  mkl                       2020.2                      256  
  mkl-service               2.3.0            py37he8ac12f_0  
  mkl_fft                   1.3.0            py37h54f3939_0  
  mkl_random                1.1.1            py37h0573a6f_0  
  mmcv                      1.0.3                    pypi_0    pypi
  ncurses                   6.2                  he6710b0_1  
  nettle                    3.6                  he412f7d_0    conda-forge
  ninja                     1.10.2               hff7bd54_1  
  numpy                     1.19.2           py37h54aff64_0  
  numpy-base                1.19.2           py37hfa32c7d_0  
  oauthlib                  3.1.0                    pypi_0    pypi
  olefile                   0.46                     py37_0  
  opencv-python             4.5.1.48                 pypi_0    pypi
  openh264                  2.1.1                h780b84a_0    conda-forge
  openselfsup               0.3.0+df3689d             dev_0    <develop>
  openssl                   1.1.1k               h7f98852_0    conda-forge
  packaging                 20.9                     pypi_0    pypi
  pillow                    6.2.2                    pypi_0    pypi
  pip                       21.0.1           py37h06a4308_0  
  protobuf                  4.0.0rc2                 pypi_0    pypi
  pyasn1                    0.4.8                    pypi_0    pypi
  pyasn1-modules            0.2.8                    pypi_0    pypi
  pyparsing                 3.0.0b2                  pypi_0    pypi
  python                    3.7.10               hdb3f193_0  
  python-dateutil           2.8.1                    pypi_0    pypi
  python_abi                3.7                     1_cp37m    conda-forge
  pytorch                   1.8.1           py3.7_cuda11.1_cudnn8.0.5_0    pytorch
  pyyaml                    5.4.1                    pypi_0    pypi
  readline                  8.1                  h27cfd23_0  
  requests                  2.25.1                   pypi_0    pypi
  requests-oauthlib         1.3.0                    pypi_0    pypi
  rsa                       4.7.2                    pypi_0    pypi
  scikit-learn              0.24.1                   pypi_0    pypi
  scipy                     1.6.2                    pypi_0    pypi
  setuptools                52.0.0           py37h06a4308_0  
  six                       1.15.0           py37h06a4308_0  
  sklearn                   0.0                      pypi_0    pypi
  sqlite                    3.35.4               hdfb4753_0  
  tensorboard               2.5.0                    pypi_0    pypi
  tensorboard-data-server   0.6.0                    pypi_0    pypi
  tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
  threadpoolctl             2.1.0                    pypi_0    pypi
  tk                        8.6.10               hbc83047_0  
  torchaudio                0.8.1                      py37    pytorch
  torchvision               0.9.1                py37_cu111    pytorch
  tqdm                      4.60.0                   pypi_0    pypi
  typing-extensions         3.7.4.3                  pypi_0    pypi
  typing_extensions         3.7.4.3                    py_0    conda-forge
  urllib3                   1.26.4                   pypi_0    pypi
  werkzeug                  2.0.0rc4                 pypi_0    pypi
  wheel                     0.36.2                   pypi_0    pypi
  xz                        5.2.5                h7b6447c_0  
  yapf                      0.31.0                   pypi_0    pypi
  zipp                      3.4.1                    pypi_0    pypi
  zlib                      1.2.11               h7b6447c_3  
  zstd                      1.4.9                haebb681_0

**Comment by Jiahao000** [comment]
It is normal that such a warning will occur sometimes, you may ignore it as it does not affect the performance.

**Comment by opsiff** [comment]
But sometimes the program is like sleeping and it cost 0% cpu  when it occurs,then I have to use CTRL+C to stop the program. 
- Detail

+ CFG=configs/selfsup/simclr/r50_bs256_ep200.py
+ PRETRAIN=pretrains/simclr_r50_bs256_ep200-4577e9a6.pth
+ FEAT_LIST=feat5
+ GPUS=1
++ echo configs/selfsup/simclr/r50_bs256_ep200
++ sed -e s/configs/work_dirs/g
++ echo pretrains/simclr_r50_bs256_ep200-4577e9a6.pth
++ rev
++ cut -d/ -f 1
++ rev
+ WORK_DIR=work_dirs/selfsup/simclr/r50_bs256_ep200/simclr_r50_bs256_ep200-4577e9a6.pth
+ '[' configs/selfsup/simclr/r50_bs256_ep200.py == '' ']'
+ '[' pretrains/simclr_r50_bs256_ep200-4577e9a6.pth == '' ']'
+ '[' '!' -f pretrains/simclr_r50_bs256_ep200-4577e9a6.pth ']'
+ mkdir -p work_dirs/selfsup/simclr/r50_bs256_ep200/simclr_r50_bs256_ep200-4577e9a6.pth/logs
+ echo 'Testing pretrain: pretrains/simclr_r50_bs256_ep200-4577e9a6.pth'
+ tee -a work_dirs/selfsup/simclr/r50_bs256_ep200/simclr_r50_bs256_ep200-4577e9a6.pth/logs/eval_svm.log
Testing pretrain: pretrains/simclr_r50_bs256_ep200-4577e9a6.pth
+ bash tools/dist_extract.sh configs/selfsup/simclr/r50_bs256_ep200.py 1 work_dirs/selfsup/simclr/r50_bs256_ep200/simclr_r50_bs256_ep200-4577e9a6.pth --pretrained pretrains/simclr_r50_bs256_ep200-4577e9a6.pth
+ PYTHON=python
+ CFG=configs/selfsup/simclr/r50_bs256_ep200.py
+ GPUS=1
+ WORK_DIR=work_dirs/selfsup/simclr/r50_bs256_ep200/simclr_r50_bs256_ep200-4577e9a6.pth
+ PY_ARGS='--pretrained pretrains/simclr_r50_bs256_ep200-4577e9a6.pth'
+ PORT=29500
+ python -m torch.distributed.launch --nproc_per_node=1 --master_port=29500 tools/extract.py configs/selfsup/simclr/r50_bs256_ep200.py --layer-ind 0,1,2,3,4 --work_dir work_dirs/selfsup/simclr/r50_bs256_ep200/simclr_r50_bs256_ep200-4577e9a6.pth --launcher pytorch --pretrained pretrains/simclr_r50_bs256_ep200-4577e9a6.pth
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 312/312, 10.0 task/s, elapsed: 31s, ETA:     0s+ bash benchmarks/svm_tools/eval_svm_full.sh work_dirs/selfsup/simclr/r50_bs256_ep200/simclr_r50_bs256_ep200-4577e9a6.pth feat5
+ set -e
+ WORK_DIR=work_dirs/selfsup/simclr/r50_bs256_ep200/simclr_r50_bs256_ep200-4577e9a6.pth
+ FEAT_LIST=feat5
+ TRAIN_SVM_FLAG=true
+ TEST_SVM_FLAG=true
+ DATA=data/VOCdevkit/VOC2007/SVMLabels
+ costs=1.0,10.0,100.0
+ for feat in $FEAT_LIST
+ echo 'For feature: feat5'
+ tee -a work_dirs/selfsup/simclr/r50_bs256_ep200/simclr_r50_bs256_ep200-4577e9a6.pth/logs/eval_svm.log
For feature: feat5
+ true
+ rm -rf work_dirs/selfsup/simclr/r50_bs256_ep200/simclr_r50_bs256_ep200-4577e9a6.pth/svm
+ mkdir -p work_dirs/selfsup/simclr/r50_bs256_ep200/simclr_r50_bs256_ep200-4577e9a6.pth/svm/voc07_feat5
+ echo 'training svm ...'
training svm ...
+ python benchmarks/svm_tools/train_svm_kfold_parallel.py --data_file work_dirs/selfsup/simclr/r50_bs256_ep200/simclr_r50_bs256_ep200-4577e9a6.pth/features/voc07_trainval_feat5.npy --targets_data_file data/VOCdevkit/VOC2007/SVMLabels/train_labels.npy --costs_list 1.0,10.0,100.0 --output_path work_dirs/selfsup/simclr/r50_bs256_ep200/simclr_r50_bs256_ep200-4577e9a6.pth/svm/voc07_feat5
  1%|█▉                                                                                                   

**The process will randomly stop and never updated,the cpu usage will come to 0%.**
                                                                                                                                       
- Hardware Information
 CPU: AMD Ryzen 5800H
 GPU: RTX 3060 Laptop @80W
 RAM: 16GB
- File Information
  md5sum simclr_r50_bs256_ep200-4577e9a6.pth 
 4015e21e3699ae41cfdd99f35b93c9da  simclr_r50_bs256_ep200-4577e9a6.pth

**Comment by opsiff** [comment]
I solve the problem by change benchmarks/svm_tools/train_svm_kfold_parallel.py in pool=mp.Pool(1) to make cpu work from parallel to serial.
But I did not understand why it works.

**Comment by Jiahao000** [comment]
Did you run other programs simultaneously on the same machine? They may hang on the program due to the cpu usage.

**Comment by opsiff** [comment]
> Did you run other programs simultaneously on the same machine? They may hang on the program due to the cpu usage.

Doesn't seem to be the problem.If I have time, I will investigate the cause of this problem.
