### ISSUE TITLE
DensePose

### ISSUE THREAD

**Issue by mseyfi** [open-mmlab/mmselfsup#104]
Hi, thanks for posting this very useful codebase. Can I also ask for the Denspose config yaml files?

**Comment by XiaohangZhan** [comment]
This repo focuses on self-supervised representation learning. DensePose might not belong to this.

**Comment by mseyfi** [comment]
I understand It is common to fine-tune the learned model on downstream tasks like detection, ... Densepose is one of them.
You have all the configs for detection, segmentation, even keypoint detection.
