### ISSUE TITLE
Initial labels

### ISSUE THREAD

**Issue by snubeaver** [open-mmlab/mmselfsup#109]
I am not quite sure how the initial labels for memories are initialized for odc. To make it online I guess it should be initialized to zeros or random numbers but doesn't seem like it.

**Comment by Jiahao000** [comment]
They are initialized via k-means. Please check [deepcluster_hook.py](https://github.com/open-mmlab/OpenSelfSup/blob/master/openselfsup/hooks/deepcluster_hook.py#L71).

**Comment by snubeaver** [comment]
Thanks for reply. Just to make sure, is the model using   all samples for  initial k-mean?

**Comment by Jiahao000** [comment]
Yes, you're right.
