### ISSUE TITLE
Downstream task Object Detection

### ISSUE THREAD

**Issue by MariaKalt** [open-mmlab/mmselfsup#111]
Can you tell me how to use OpenSelfSup for object detection with my own dataset?
Is it possible with the library or do I need to combine the self-supervised Learning and object detection myself?

I would be very grateful for any help!

**Comment by Jiahao000** [comment]
You need to combine by yourself for object detection with the custom dataset.

**Comment by MariaKalt** [comment]
Thank you for the clarification!
