### ISSUE TITLE
lr_config supports SimSiam

### ISSUE THREAD

**Issue by weivision** [open-mmlab/mmselfsup#116]
Hi, 

Recently, I am trying to reproduce SimSiam using OpenSelfSup but not quite familiar with the open-mmcv package. May I ask how to implement the lr_config that supports SimSiam?  In the official implementation, the learning rate of the encoder is tuned based on cos policy, while keeping the predictor's lr fixed.

https://github.com/facebookresearch/simsiam/blob/a7bc1772896d0dad0806c51f0bb6f3b16d290468/main_simsiam.py#L359

**Comment by Jiahao000** [comment]
Hi, you need to write a lr updater hook to set different lr schedules for the encoder and the predictor. You can refer to [this link](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/lr_updater.py) for your implementation.

**Comment by weivision** [comment]
Many thanks. Indeed, writing a specific lr_updater_hook seems the most elegant way to implement this feature.
