### ISSUE TITLE
ODC forward_test differs from forward_train

### ISSUE THREAD

**Issue by ardywibowo** [open-mmlab/mmselfsup#117]
Hello,
I believe `forward_test()` in `odc.py` should have `x = self.neck(x)`. It should be:

```
x = self.forward_backbone(img)  # tuple
x = self.neck(x)
outs = self.head(x)
```

Otherwise, testing throws a shape error if the output sizes of `head` and `neck` are different. Is this correct?

**Comment by Jiahao000** [comment]
We do not add `x = self.neck(x)` here since the quality of backbone features is usually evaluated. In this case, you should change `in_channels` in `head` accordingly in your config. If you want to evaluate the features after `neck`, you can customize by adding `x = self.neck(x)` here.

**Comment by ardywibowo** [comment]
Thanks!

I see, so we should use `forward_backbone` instead of `forward_test` to get the representations? Is there any use for forward `forward_test` for ODC? I was using the default config `configs/selfsup/odc/r50_v1.py` which gave the error using `forward_test`. It was unclear whether this was intended or not.

**Comment by Jiahao000** [comment]
Actually, there is no test stage during pre-training. We leave `forward_test` here for reference only in case you want to realize some other functions (e.g., evaluate/visualize some tensors). The default config is for pre-training only. You can customize your config accordingly.

**Comment by ardywibowo** [comment]
I wonder if it would be useful to note this in the module, like a warning or comment. Thanks for the answer! I'll close this issue.
