### ISSUE TITLE
Difference between built-in `multinomial` and `alias_multinomial`?

### ISSUE THREAD

**Issue by whatever60** [open-mmlab/mmselfsup#120]
Hi. Great repo.

In face I got this question when reading the original NPID repo, which is built on pytorch 0.4 and contains the `alias_multinomial` class to sample from multinomial distribution. Now that pytorch already has built in multinomial method, why is `alias_multinomial` still used? (it seems that the built in method is much faster)

Looking forward to your reply.

**Comment by Jiahao000** [comment]
Hi, we originally follow the official repo to use `alias_multinomial` for NPID implementation. Of course, you can try pytorch built-in `multinomial` method.

**Comment by whatever60** [comment]
So it's to keep things consistent with the official repo. That's nice.
