### ISSUE TITLE
Have you published pretrained weights with proj heads

### ISSUE THREAD

**Issue by CoinCheung** [open-mmlab/mmselfsup#124]
Hi,

I would like to extract features from byol pretrained models. I downloaed `byol_r50_bs256_accmulate16_ep300-5df46722.pth`, which only contains weights for resnet50, and the others features are all missing. Where could I download complete pretrained weights please ?

**Comment by Jiahao000** [comment]
Hi, you need to retrain by yourself if you want to obtain other weights.
