### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by NickChang97** [open-mmlab/mmselfsup#125]
https://github.com/open-mmlab/OpenSelfSup/blob/1db69ecebbc129e8fa90cdcea6f2082f0a4e3d17/openselfsup/datasets/classification.py#L37

when k is 5, the tensor is not contiguous. 
if I changed it to `correct_k = correct[:k].contiguous().view(-1).float().sum(0).item()` 
it works

**Comment by Jiahao000** [comment]
Thanks for pointing out. We will fix it.
