### ISSUE TITLE
Will this repo be updated continuously?

### ISSUE THREAD

**Issue by luuuyi** [open-mmlab/mmselfsup#128]
As title.

First, this is a best repo cause many popular methods are integrated in it. So, I want to konw will this repo be updated continuously. Such as any plan to integrate SwAV?

**Comment by 4-0-4-notfound** [comment]
Same ask here

**Comment by Jiahao000** [comment]
Hi, sorry for the late reply, we are planning to upgrade the repo and integrate more methods. Please stay tuned!
