### ISSUE TITLE
Question about detectron2 evaluation

### ISSUE THREAD

**Issue by NickChang97** [open-mmlab/mmselfsup#130]
Hi, according to the COCO evaluation doc,that propose to must use 8GPUS.  Because of the machine limit, I change to 4 GPUS, but the total batch size is 16 yet. And all of the BN is SyncBN, howerer I get a different results compared to standard 8 GPUS. Can you give some suggestions. Thanks in advance

**Comment by fangyixiao18** [comment]
Sorry for late reply. Can you provide the difference of your results?

**Comment by NickChang97** [comment]
For moco v2, 39.8% AP for 4 GPUs and 38.8% AP for  8 GPUs.

**Comment by NickChang97** [comment]
The config file is "mmselfsup/configs/benchmarks/detectron2/coco_R_50_FPN_1x_moco.yaml"

**Comment by ZwwWayne** [comment]
Hi @NickChang97 ,
Do you modify any other settings in the config? Could you post your log for us to compare the difference if you can?
Theoretically, there should be no difference in the performance if you use SyncBN.

**Comment by NickChang97** [comment]
> Hi @NickChang97 , Do you modify any other settings in the config? Could you post your log for us to compare the difference if you can? Theoretically, there should be no difference in the performance if you use SyncBN.

Hi, no any modify, I only don't use the standard R50 backbone.  For standard resnet50, it 39.0 AP for 4 GPUs and 38.8 AP for 8 GPUs

**Comment by NickChang97** [comment]
The log is too long to post here, which part are you interested in?
