### ISSUE TITLE
Do you plan to make the framework support small datasets like Cifar, STL-10, ImageNet-Tiny, etc?

### ISSUE THREAD

**Issue by liming-ai** [open-mmlab/mmselfsup#131]

**Comment by fangyixiao18** [comment]
Thanks for your suggestion and we will discuss it.
Now we have ImageList datasource for convenience to load custom datasets.
Please refer to https://github.com/open-mmlab/mmselfsup/blob/master/mmselfsup/datasets/data_sources/image_list.py
