### ISSUE TITLE
Guide on SSL Pretraining ResNet50 Caffe for Object Detection on Custom Dataset

### ISSUE THREAD

**Issue by sarmientoj24** [open-mmlab/mmselfsup#132]
I am using ResNet 50 Caffe for object detection with MMDetection. I am wondering if I can possibly pretrain that ResNet 50 Caffe model COCO on my *custom dataset* and if there is any guide to it

**Comment by fangyixiao18** [comment]
Sorry for late reply. We now offered the image_list.py file for custom datasets or you can write your own dataset. We have some tutorials which might help. 
The links are listed below.
https://github.com/open-mmlab/mmselfsup/blob/master/mmselfsup/datasets/data_sources/image_list.py
https://github.com/open-mmlab/mmselfsup/tree/master/docs/en/tutorials
