### ISSUE TITLE
Will the community support more non-contrastive SSL methods?

### ISSUE THREAD

**Issue by Adenialzz** [open-mmlab/mmselfsup#135]
**Describe the feature**
Will the community consider supporting more non-contrastive self-supervised methods, such as the earlier Jigsaw Puzzle, RotNet, etc.?

**Motivation**
Some generative, semantic-based methods are also an important part of self-supervised learning. Will the community consider supporting more of these methods?

**Comment by Jiahao000** [comment]
Hi, thanks for your suggestion. We have supported some earlier non-contrastive methods as mentioned like RelPatchLoc, RotNet. More recent methods like MAE, etc., are in our plan. We would appreciate it if you could implement new methods or add new features to MMSelfSup.

**Comment by Adenialzz** [comment]
Thanks for your reply. Looking forward to the implementation of the latest method. And We will contribute the repo if there is an opportunity.
