### ISSUE TITLE
there is an error when downloading the cifar dataset

### ISSUE THREAD

**Issue by CharisWg** [open-mmlab/mmselfsup#147]
I got two errors when trying to use python cifar.py.
are they related to DATASOURCES = Registry('datasource')? 
can someone help me to solve it?
![1](https://user-images.githubusercontent.com/51305074/146384408-77200924-aae3-4364-ae29-5c3a1d224697.png)

![2](https://user-images.githubusercontent.com/51305074/146384434-4bb444be-42f9-449c-83f3-04cd5700fede.png)

**Comment by fangyixiao18** [comment]
Hello, sorry for the late reply. 
1. Yes, as you run the cifar.py directly, the registry mechanism is not initialized. You can follow our tutorial to run the codes.
2. The second is warning to tell users the API in mmcv will be updated.
