### ISSUE TITLE
Requiring train logs and training time per epoch

### ISSUE THREAD

**Issue by holyseven** [open-mmlab/mmselfsup#156]
Hi,

Thanks for the work, great repo!

I am wondering whether the train logs were still kept. Those logs have been provided in other mm-lab projects, such as [mmseg](https://github.com/open-mmlab/mmsegmentation/tree/master/configs/deeplabv3plus#cityscapes). It would be great to have those logs, so that we could quickly compare with our own experiments and find problems in a few epochs.

Meanwhile, the time cost per epoch is expected too. I found this info in the [previous docs](https://github.com/open-mmlab/mmselfsup/blob/ed5000482b0d8b816cd8a6fbbb1f97da44916fed/docs/MODEL_ZOO.md#pre-trained-model-download-links-and-speed-test), but not current version. Are those numbers counted in the same setting? This info could give us a rough comparison for those existing algorithms.

BTW, one typo is [found](https://github.com/open-mmlab/mmselfsup/blob/master/configs/selfsup/densecl/densecl_resnet50_8xb32-coslr-200e_in1k.py#L2), where a comma is missed too.

**Comment by YuanLiuuuuuu** [comment]
Thank you for pointing out this typo, and  we will fix it. As for the train logs, I will contact the corresponding person. Please stay tuned ~
