### ISSUE TITLE
 A problem with simclr implementation

### ISSUE THREAD

**Issue by lzyhha** [open-mmlab/mmselfsup#159]
At the line 72 in simclr.py, the images are concatenated together, with order "0 1 ... N-1 0 1 ... N-1". So I think the positive indexes should be "N-1 N N+1 ... 2N-2 0 1 2 3 ... N-1". However, the positive indexes  is "0 0  2 2 4 4... 2N-2 2N-2" in the code. 
I'm not sure about this, looking forward to your reply.

**Comment by fangyixiao18** [comment]
Thank your for your comment, it is actually a bug and I also find it today while training simclr for its training logs. It will be fixed soon!

**Comment by lzyhha** [comment]
这是来自QQ邮箱的自动回复邮件。This is a automatic response.
