### ISSUE TITLE
Progress of Chinese Documentation

### ISSUE THREAD

**Issue by fangyixiao18** [open-mmlab/mmselfsup#162]
We are building Chinese Documentation now, PRs of translation from the community are welcomed.
To make the community fully aware of the progress, we list the progress here. Please feel free to leave a message and create a PR if you are willing to translate any one of the documentation.

- [x] docs/zh_cn/tutorials/0_config.md
- [x] docs/zh_cn/tutorials/1_new_dataset.md
- [x] docs/zh_cn/tutorials/2_data_pipeline.md
- [x] docs/zh_cn/tutorials/3_new_module.md
- [x] docs/zh_cn/tutorials/4_schedule.md
- [x] docs/zh_cn/tutorials/5_runtime.md
- [x] docs/zh_cn/tutorials/6_benchmarks.md

Thanks to all.

**Comment by RangeKing** [comment]
I created a PR - https://github.com/open-mmlab/mmselfsup/pull/163 to translate docs/zh_cn/tutorials/1_new_dataset.md into into Chinese. If such a Chinese Documentation is OK, I'll try to translate more documents.

**Comment by YuanLiuuuuuu** [comment]
> I created a PR - #163 to translate docs/zh_cn/tutorials/1_new_dataset.md into into Chinese. If such a Chinese Documentation is OK, I'll try to translate more documents.

Many thanks to you. We will review your PR as soon as possible.
