### ISSUE TITLE
SyncBN or BN ? 

### ISSUE THREAD

**Issue by liming-ai** [open-mmlab/mmselfsup#185]
I noticed that in different configs, sometimes SyncBN is used, while others are BN.

For example, SyncBN is used for simclr, simsiam, byol, swav; BN is used for mocov1, mocov2, densecl

I think SyncBN would be a better option when using multiple GPUs, so what is the reason for using BN instead of SyncBN here for mocov1, mocov2 and densecl?

For MoCo, the original paper uses shuffle BN. For densecl, the original paper states that SyncBN is used, yet both the source code and the mmselfsup configuration file only use BN, which is very confusing to me.

**Comment by fangyixiao18** [comment]
We re-implemented the algorithms following the official settings, as the moco doesn't use SyncBN. As for densecl, we will check it later.

**Comment by Jiahao000** [comment]
For DenseCL, I think the original paper does not state that SyncBN is used during pre-training. It follows the MoCo framework to use shuffle BN.

**Comment by liming-ai** [comment]
Sorry to bother you, SyncBN is used in the downstream detection and segmentation tasks, not in the pre-training phase as I thought before.
