### ISSUE TITLE
MOCO imagenet linear classification

### ISSUE THREAD

**Issue by ruotianluo** [open-mmlab/mmselfsup#19]
Hi,

In the moco repo, they use lr 30, while it seems you use 0.1 by default. Did you get the results in the model zoo with lr 0.1?

**Comment by ruotianluo** [comment]
Never mind, I found the wrong config.

**Comment by ruotianluo** [comment]
I guess the question then would be, do you use https://github.com/open-mmlab/OpenSelfSup/blob/master/configs/benchmarks/linear_classification/imagenet/r50_moco.py config for other methods like simclr?

**Comment by XiaohangZhan** [comment]
Yes, `moco` here means using the evaluation setting in moco. I think I should rename it.

**Comment by XiaohangZhan** [comment]
It has been renamed as `r50_last.py`
