### ISSUE TITLE
[Refactor] Deprecate imgs_per_gpu and use samples_per_gpu

### ISSUE THREAD

**Issue by ZwwWayne** [open-mmlab/mmselfsup#202]
**Describe the feature**

**Motivation**
OpenMMLab projects have already deprecated imgs_per_gpu and use samples_per_gpu.
To be consistent with other projects so that mmselfsup could share similar API, mmselfsup should also use samples_per_gpu.

**Related resources**
See https://github.com/open-mmlab/mmdetection/pull/2700

**Comment by fangyixiao18** [comment]
ok, I will create a PR.
