### ISSUE TITLE
[Bug Report]  cfg-options doesn't work when change input_size

### ISSUE THREAD

**Issue by liming-ai** [open-mmlab/mmselfsup#203]
Hi @XiaohangZhan @Jiahao000 ~, Happy new year (dog

I want to change the input size during training DenseCL, so I add following command:
```
--cfg-options train_pipeline.0.size=384
```
However, I found the training loss doesn't change and I found this mismatch between `train_pipeline` and `data.train.pipelines` in log. This issue also exist in other selfsup methods.

---
For `train_pipeline`, the `input_size` is changed to 384
```
train_pipeline = [
    dict(type='RandomResizedCrop', size=384, scale=(0.2, 1.0)),
    dict(
        type='RandomAppliedTrans',
        transforms=[
            dict(
                type='ColorJitter',
                brightness=0.4,
                contrast=0.4,
                saturation=0.4,
                hue=0.1)
        ],
        p=0.8),
    dict(type='RandomGrayscale', p=0.2),
    dict(type='GaussianBlur', sigma_min=0.1, sigma_max=2.0, p=0.5),
    dict(type='RandomHorizontalFlip'),
    dict(type='ToTensor'),
    dict(
        type='Normalize',
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225])
]
```
---
For `data.train.pipelines`, the `input_size` is still 224:
```
data = dict(
    imgs_per_gpu=32,
    workers_per_gpu=4,
    drop_last=True,
    train=dict(
        type='MultiViewDataset',
        data_source=dict(
            type='ImageNet',
            data_prefix='data/imagenet/train',
            ann_file='data/imagenet/meta/train.txt'),
        num_views=[2],
        pipelines=[[{
            'type': 'RandomResizedCrop',
            'size': 224,
            'scale': (0.2, 1.0)
        }, {
        ......
```

**Comment by fangyixiao18** [comment]
Actually, due to the limitation of `mmcv`, the `--cfg-options` only supports to modify the `dict` object defined in config files, but the `train_pipeline` is defined as a `list` object.

**Comment by fangyixiao18** [comment]
You can use command `--cfg-options data.train.pipelines.0.0.size=384` to change the input size.

**Comment by fangyixiao18** [comment]
Besides, when train.py starts to run, the config has been loaded to memory and the train_pipeline is useless, you need to modify the config loaded by the code here.
https://github.com/open-mmlab/mmselfsup/blob/cea50785e1fd63894f6cea92e9c148469879542e/tools/train.py#L77-L79

**Comment by liming-ai** [comment]
> You can use command `--cfg-options data.train.pipelines.0.0.size=384` to change the input size.

It works, but the input size is still 224 for `data.train.pipelines` in log, I think it may confuse user, since the input size is mismatch between `train_pipeline` and `data.train.pipelines`.

**Comment by fangyixiao18** [comment]
Due to the limitation of `mmcv`, it prints all the config in the log currently. We will discuss it and it might be improved in the future version.
Thanks for your valuable comments.

**Comment by liming-ai** [comment]
glad to know that, maybe this example could be put in tutorial~
