### ISSUE TITLE
BGR used in pretraining but RGB used in downstream tasks

### ISSUE THREAD

**Issue by holyseven** [open-mmlab/mmselfsup#205]
As I understand, the channel_order is not adjusted in the SSL pre-training stage, e.g., [MoCoV2](https://github.com/open-mmlab/mmselfsup/blob/master/configs/selfsup/_base_/datasets/imagenet_mocov2.py), and BGR is always used because of the opencv backend. However, in the downstream tasks, e.g., [cityscapes](https://github.com/open-mmlab/mmselfsup/blob/master/configs/benchmarks/mmsegmentation/_base_/datasets/cityscapes.py#L4-L5), `to_rgb` is set to `True`.

Tell me if I missed something. Otherwise it's better to have a consistent configuration. (Maybe this is not a big problem since improvements from SSL have been noticed.)

**Comment by fangyixiao18** [comment]
Thanks for your comments.
Actually, pre-training stage in MMSelfSup now uses torchvision transforms, which is different from other MM-projects such as MMDet. This part will be refactored in the future version, we will change it to use transforms from mmcv and the opencv backend.

**Comment by holyseven** [comment]
That would be great!

**Comment by fangyixiao18** [comment]
I made a mistake, there is a bug here, the loaded images is BGR format. We will fix it as soon as possible.
Thanks again !!

**Comment by holyseven** [comment]
Maybe add `channel_order='rgb'` when [loading images](https://github.com/open-mmlab/mmselfsup/blob/v0.6.0/mmselfsup/datasets/data_sources/base.py#L94) is a temporal solution.

But this would be totally fixed after changing to mmcv transforms.

**Comment by liming-ai** [comment]
@fangyixiao18  Will this bug make the previously trained self-supervised model unusable? Or, do we need to retrain all the self-supervised models ?

**Comment by liming-ai** [comment]
I found that both mmcv and mmdet use `BGR` by default, so maybe there is no need to retrain the backbone, only to change the `to_rgb` to `False` in config files. Please refer to this [issue](https://github.com/open-mmlab/mmdetection/issues/6735) in MMDet
