### ISSUE TITLE
How can I train with my own dataset?

### ISSUE THREAD

**Issue by ACbccc** [open-mmlab/mmselfsup#211]
Hello! I want to use mmselfsup to improve the performance of detection with my own dataset-part2. For using mmselfsup to train a pre-trained model, I transformed my dataset-part1 to imagenet type first, and want to modify the config of mocov2 for training. But I see "ann_file='data/imagenet/meta/train.txt'," in imagenet_mococ2.py. In fact I don't have any annotations with my dataset-part1 like imagenet but have some voc type annotations with my dataset-part2. How can I begin my training work? Thank you!

**Comment by wang11wang** [comment]
The train.txt should be as the document described in here:
https://mmselfsup.readthedocs.io/en/latest/tutorials/1_new_dataset.html#an-example-of-customized-dataset
