### ISSUE TITLE
Why can't training? ImportError: cannot import name '__version__' from 'mmselfsup' (unknown location)

### ISSUE THREAD

**Issue by kkellyk** [open-mmlab/mmselfsup#214]
I have downloaded all the required packages:
python 3.7.11
pytorch 1.10.2
cuda 10.2
cudnn 7.6.5
mmcv-full 1.4.5
Tensorflow-gpu 1.14

And I try to run the tools/train.py in Anaconda Prompt(Anaconda3).
As shown below:
> (openmmlab)` C:\Users\name\mmselfsup>python tools/train.py  configs/selfsup/odc/odc_resnet50_8xb64-steplr-440e_in1k.py
> Traceback (most recent call last):
>   File "tools/train.py", line 14, in <module>
>     from mmselfsup import __version__
> ImportError: cannot import name '__version__' from 'mmselfsup' (unknown location)

But when I execute from mmselfsup import __version__ in Jupyter Notebook (openmmlab), no error will be generated
I have already executed pip install Pillow

Below is my path folder:
- C:\Users\name
     - .conda
     - .ipython
     - .jupyter
     - .keras
     - mmselfsup
         -configs
         -....
         -tools.....

Please is anyone could help me?
Thank you

**Comment by fangyixiao18** [comment]
Did you confirm the PYTHON PATH?
