### ISSUE TITLE
[Memory Leak]The memory of the program grows larger during training and lead to memory overflow.

### ISSUE THREAD

**Issue by liming-ai** [open-mmlab/mmselfsup#217]
@scnuhealthy @XiaohangZhan @fangyixiao18 @xieenze @Jiahao000 

Thanks for reporting the unexpected results and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The unexpected results still exist in the latest version.

**Describe the Issue**

I am trying to use ImageNet-22k to train DenseCL with standard R50 for 400 epochs, `htop` is used to monitored the system status, I noticed that the `Mem` (RAM) is enlarged during the training and finally lead to a memory overflow.

I tried to set `pin_memory = False` in [`mmselfsup/apis/train.py`](https://github.com/open-mmlab/mmselfsup/blob/af331b043fa6f81037181a83bf8dd38e28bd65c6/mmselfsup/apis/train.py#L104) and add it into config. However, the allocated memory still enlarged and finally cause memory overflow.

I haven't changed any code except config if I keep the `pin_memory=True`, but the error still occurs.

**Reproduction**

1. What command, code, or script did you run?

```bash
bash tools/dist_train.sh configs/selfsup/densecl/densecl_resnet50_8xb128-coslr-200e_in22k.py 8 --work_dir work_dirs/mmselfsup/densecl/densecl_resnet50_8xb128-coslr-200e_in22k_fp16 --deterministic
```

The config is:
```
_base_ = [
    '../_base_/models/densecl.py',
    '../_base_/datasets/imagenet_mocov2.py',
    '../_base_/schedules/sgd_coslr-200e_in1k.py',
    '../_base_/default_runtime.py',
]

# runtime settings
checkpoint_config = dict(interval=10)

# base lr is 0.03 for total batch size 256
optimizer = dict(type='SGD', lr=0.12, weight_decay=1e-4, momentum=0.9)

# training epochs
runner = dict(type='EpochBasedRunner', max_epochs=200)

# fp16
fp16 = dict(loss_scale='dynamic')

# following BEiT
img_norm_cfg = dict(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])

# dataset summary
data = dict(
    samples_per_gpu=128,  # total 128*8=1024
    workers_per_gpu=8,
    drop_last=True,
    pin_memory=False,
    train=dict(
        data_source=dict(
            data_prefix='data/ImageNet-22k/train',
            ann_file='data/ImageNet-22k/train.txt',
        ),
    ))
```

2. Did you make any modifications on the code? Did you understand what you have modified?

Yes, I modify the code and change the `pin_memory` to `False`, but it doesn't work.

**Environment**

<details>
<summary>Click to toggle the environment</summary>
{'sys.platform': 'linux', 'Python': '3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]', 'CUDA available': True, 'GPU 0,1,2,3,4,5,6,7': 'Tesla V100-SXM2-32GB', 'CUDA_HOME': '/usr/local/cuda', 'NVCC': 'Build cuda_11.3.r11.3/compiler.29920130_0', 'GCC': 'gcc (Debian 8.3.0-6) 8.3.0', 'PyTorch': '1.10.0.post1', 'PyTorch compiling details': 'PyTorch built with:\n  - GCC 7.3\n  - C++ Version: 201402\n  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: AVX512\n  - CUDA Runtime 11.3\n  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86\n  - CuDNN 8.2\n  - Magma 2.5.2\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, \n', 'TorchVision': '0.11.1+cu113', 'OpenCV': '4.5.5', 'MMCV': '1.4.5', 'MMCV Compiler': 'GCC 7.3', 'MMCV CUDA Compiler': '11.3', 'MMSelfSup': '0.6.0+'}
</details>

**Error traceback**

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Advice**
We can add `pin_memory=cfg.data.pin_memory` [here](https://github.com/open-mmlab/mmselfsup/blob/af331b043fa6f81037181a83bf8dd38e28bd65c6/mmselfsup/apis/train.py#L104) to support modify `pin_memory` in config.

**Comment by fangyixiao18** [comment]
Thank you for your issue!
You can set smaller number of `workers_per_gpu`, maybe 4 or 2, it can alleviate the issue but doesn't solve it.
Besides, MMClassification has the same issue, you can refer to this [PR link](https://github.com/open-mmlab/mmclassification/pull/461) to try it by yourself, it will help.
Here is another issue link related: https://github.com/pytorch/pytorch/issues/13246#issuecomment-445770039

**Comment by liming-ai** [comment]
> Thank you for your issue! You can set smaller number of `workers_per_gpu`, maybe 4 or 2, it can alleviate the issue but doesn't solve it. Besides, MMClassification has the same issue, you can refer to this [PR link](https://github.com/open-mmlab/mmclassification/pull/461) to try it by yourself, it will help. Here is another issue link related: [pytorch/pytorch#13246 (comment)](https://github.com/pytorch/pytorch/issues/13246#issuecomment-445770039)

@fangyixiao18 , thanks for your reply.

Does mmcls solve this problem? If so, can you provide a solution or a PR link? If not, can you give me the reason for the problem? 

I have checked the link you gave, but it seems to be only to make mmcls support ImageNet-22k, not to solve the above problem.

Also, I did not find this problem on ImageNet-1k, which is quite confusing to me. It seems only the big datasets occur the issue.

**Comment by fangyixiao18** [comment]
When mmcls supports this dataset, they found this problem, so they implemented it like the PR that I mentioned. From this implementation, the model can be trained on our own cluster. 

> Also, I did not find this problem on ImageNet-1k, which is quite confusing to me. It seems only the big datasets occur the issue.

Yes, it might be caused by pytorch dataloader. It has some explanation in the pytorch link that I gave you.

**Comment by liming-ai** [comment]
I referenced and tried the mmcls implementation, which does reduce memory usage. However, the memory leak problem was not solved.

> From this implementation, the model can be trained on our own cluster.

Has the memory leak been addressed in your experiments with the mmcls implementation? Or is it like me, only mitigating the problem, not solving it.

Thanks again for your reply and contribution.

**Comment by fangyixiao18** [comment]
Actually, it is just mitigated but not solved. 
We have an experiment result, if you change the original type of `data_infos` from `list[dict]` to `np.array(np.string)`, it might be solved. But you need to write your own codes, we don't support it currently.
[dataloader_mem_leak_copy-on-access_problem.pdf](https://github.com/open-mmlab/mmselfsup/files/8124000/dataloader_mem_leak_copy-on-access_problem.pdf)

**Comment by liming-ai** [comment]
> Actually, it is just mitigated but not solved. We have an experiment result, if you change the original type of `data_infos` from `list[dict]` to `np.array(np.string)`, it might be solved. But you need to write your own codes, we don't support it currently. [dataloader_mem_leak_copy-on-access_problem.pdf](https://github.com/open-mmlab/mmselfsup/files/8124000/dataloader_mem_leak_copy-on-access_problem.pdf)

Thanks for your reply, I will try this, and if it works, I will create a PR to fix the problem.
