### ISSUE TITLE
How to use the model inside mmselfsup file? How to get started?

### ISSUE THREAD

**Issue by kkellyk** [open-mmlab/mmselfsup#220]
**I have read _getting_started.md_,But still don't understand.**
**I try to pre-trained on DOC, and I only had one GPU
the command is:**
```
(base) kellyubuntu2@kellyubuntu2-MS-7A69:~$ conda activate openmmlab
(openmmlab) kellyubuntu2@kellyubuntu2-MS-7A69:~$ cd mmselfsup
(openmmlab) kellyubuntu2@kellyubuntu2-MS-7A69:~/mmselfsup$ bash tools/dist_train.sh configs/selfsup/odc/odc_resnet50_8xb64-steplr-440e_in1k.py 1 --work_dir work_dirs/selfsup/odc/odc_resnet50_8xb64-steplr-440e_in1k/
```
**But the following output, is it correct?**

/home/kellyubuntu2/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

 FutureWarning,
/home/kellyubuntu2/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py:255: DeprecationWarning: The old API of register_module(module, force=False) is deprecated and will be removed, please use the new API register_module(name=None, force=False, module=None) instead.
  DeprecationWarning)
/home/kellyubuntu2/mmselfsup/mmselfsup/utils/setup_env.py:33: UserWarning: Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  f'Setting OMP_NUM_THREADS environment variable for each process '
/home/kellyubuntu2/mmselfsup/mmselfsup/utils/setup_env.py:43: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  f'Setting MKL_NUM_THREADS environment variable for each process '
tools/train.py:100: UserWarning: `--gpus` is deprecated because we only support single GPU mode in non-distributed training. Use `gpus=1` now.
  warnings.warn('`--gpus` is deprecated because we only support '
2022-02-25 10:11:15,203 - mmselfsup - INFO - Environment info:
------------------------------------------------------------
sys.platform: linux
Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
CUDA available: True
GPU 0: NVIDIA GeForce GTX 1060 6GB
CUDA_HOME: /usr
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
PyTorch: 1.10.2
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.3
OpenCV: 4.5.5
MMCV: 1.4.5
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.3
MMSelfSup: 0.6.0+af331b0
------------------------------------------------------------

<string>:7: DeprecationWarning: invalid escape sequence \A
2022-02-25 10:11:15,283 - mmselfsup - INFO - Distributed training: True
2022-02-25 10:11:15,360 - mmselfsup - INFO - Config:
model = dict(
    type='ODC',
    with_sobel=False,
    backbone=dict(
        type='ResNet',
        depth=50,
        in_channels=3,
        out_indices=[4],
        norm_cfg=dict(type='SyncBN')),
    neck=dict(
        type='ODCNeck',
        in_channels=2048,
        hid_channels=512,
        out_channels=256,
        with_avg_pool=True),
    head=dict(
        type='ClsHead',
        with_avg_pool=False,
        in_channels=256,
        num_classes=10000),
    memory_bank=dict(
        type='ODCMemory',
        length=1281167,
        feat_dim=256,
        momentum=0.5,
        num_classes=10000,
        min_cluster=20,
        debug=False))
data_source = 'ImageNet'
dataset_type = 'DeepClusterDataset'
img_norm_cfg = dict(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
train_pipeline = [
    dict(type='RandomResizedCrop', size=224),
    dict(type='RandomHorizontalFlip'),
    dict(type='RandomRotation', degrees=2),
    dict(
        type='ColorJitter',
        brightness=0.4,
        contrast=0.4,
        saturation=1.0,
        hue=0.5),
    dict(type='RandomGrayscale', p=0.2),
    dict(type='ToTensor'),
    dict(
        type='Normalize',
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225])
]
extract_pipeline = [
    dict(type='Resize', size=256),
    dict(type='CenterCrop', size=224),
    dict(type='ToTensor'),
    dict(
        type='Normalize',
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225])
]
prefetch = False
data = dict(
    samples_per_gpu=64,
    sampling_replace=True,
    workers_per_gpu=4,
    train=dict(
        type='DeepClusterDataset',
        data_source=dict(
            type='ImageNet',
            data_prefix='data/imagenet/train',
            ann_file='data/imagenet/meta/train.txt'),
        pipeline=[
            dict(type='RandomResizedCrop', size=224),
            dict(type='RandomHorizontalFlip'),
            dict(type='RandomRotation', degrees=2),
            dict(
                type='ColorJitter',
                brightness=0.4,
                contrast=0.4,
                saturation=1.0,
                hue=0.5),
            dict(type='RandomGrayscale', p=0.2),
            dict(type='ToTensor'),
            dict(
                type='Normalize',
                mean=[0.485, 0.456, 0.406],
                std=[0.229, 0.224, 0.225])
        ],
        prefetch=False))
num_classes = 10000
custom_hooks = [
    dict(
        type='DeepClusterHook',
        extractor=dict(
            samples_per_gpu=128,
            workers_per_gpu=8,
            dataset=dict(
                type='DeepClusterDataset',
                data_source=dict(
                    type='ImageNet',
                    data_prefix='data/imagenet/train',
                    ann_file='data/imagenet/meta/train.txt'),
                pipeline=[
                    dict(type='Resize', size=256),
                    dict(type='CenterCrop', size=224),
                    dict(type='ToTensor'),
                    dict(
                        type='Normalize',
                        mean=[0.485, 0.456, 0.406],
                        std=[0.229, 0.224, 0.225])
                ],
                prefetch=False),
            prefetch=False,
            img_norm_cfg=dict(
                mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])),
        clustering=dict(type='Kmeans', k=10000, pca_dim=-1),
        unif_sampling=False,
        reweight=True,
        reweight_pow=0.5,
        init_memory=True,
        initial=True,
        interval=9999999999),
    dict(
        type='ODCHook',
        centroids_update_interval=10,
        deal_with_small_clusters_interval=1,
        evaluate_interval=50,
        reweight=True,
        reweight_pow=0.5)
]
optimizer = dict(
    type='SGD',
    lr=0.06,
    weight_decay=1e-05,
    momentum=0.9,
    paramwise_options=dict({'\Ahead.': dict(momentum=0.0)}))
optimizer_config = dict()
lr_config = dict(policy='step', step=[400], gamma=0.4)
runner = dict(type='EpochBasedRunner', max_epochs=440)
checkpoint_config = dict(interval=10, max_keep_ckpts=3)
log_config = dict(interval=50, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
cudnn_benchmark = True
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
persistent_workers = True
opencv_num_threads = 0
mp_start_method = 'fork'
work_dir = 'work_dirs/selfsup/odc/odc_resnet50_8xb64-steplr-440e_in1k/'
gpu_ids = range(0, 1)

2022-02-25 10:11:15,360 - mmselfsup - INFO - Set random seed to 0, deterministic: False
2022-02-25 10:11:17,217 - mmselfsup - INFO - initialize ResNet with init_cfg [{'type': 'Kaiming', 'layer': 'Conv2d'}, {'type': 'Constant', 'val': 1, 'layer': ['_BatchNorm', 'GroupNorm']}]
2022-02-25 10:11:17,374 - mmselfsup - INFO - initialize ODCNeck with init_cfg [{'type': 'Constant', 'val': 1, 'layer': ['_BatchNorm', 'GroupNorm']}]
2022-02-25 10:11:17,375 - mmselfsup - INFO - initialize ClsHead with init_cfg [{'type': 'Normal', 'std': 0.01, 'layer': 'Linear'}, {'type': 'Constant', 'val': 1, 'layer': ['_BatchNorm', 'GroupNorm']}]
/home/kellyubuntu2/mmselfsup/mmselfsup/datasets/base.py:29: UserWarning: The dataset part will be refactored, it will soon support `dict` in pipelines to save more information, the same as the pipeline in `MMDet`.
  warnings.warn('The dataset part will be refactored, it will soon '
Traceback (most recent call last):
  File "/home/kellyubuntu2/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/kellyubuntu2/mmselfsup/mmselfsup/datasets/data_sources/base.py", line 43, in __init__
    self.data_infos = self.load_annotations()
  File "/home/kellyubuntu2/mmselfsup/mmselfsup/datasets/data_sources/imagenet.py", line 88, in load_annotations
    with open(self.ann_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/imagenet/meta/train.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kellyubuntu2/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/kellyubuntu2/mmselfsup/mmselfsup/datasets/deepcluster.py", line 25, in __init__
    prefetch)
  File "/home/kellyubuntu2/mmselfsup/mmselfsup/datasets/base.py", line 32, in __init__
    self.data_source = build_datasource(data_source)
  File "/home/kellyubuntu2/mmselfsup/mmselfsup/datasets/builder.py", line 32, in build_datasource
    return build_from_cfg(cfg, DATASOURCES, default_args)
  File "/home/kellyubuntu2/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
FileNotFoundError: ImageNet: [Errno 2] No such file or directory: 'data/imagenet/meta/train.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 179, in <module>
    main()
  File "tools/train.py", line 161, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/kellyubuntu2/mmselfsup/mmselfsup/datasets/builder.py", line 43, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/kellyubuntu2/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
FileNotFoundError: DeepClusterDataset: ImageNet: [Errno 2] No such file or directory: 'data/imagenet/meta/train.txt'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 74052) of binary: /home/kellyubuntu2/anaconda3/envs/openmmlab/bin/python
Traceback (most recent call last):
  File "/home/kellyubuntu2/anaconda3/envs/openmmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kellyubuntu2/anaconda3/envs/openmmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kellyubuntu2/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/kellyubuntu2/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/kellyubuntu2/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/kellyubuntu2/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/home/kellyubuntu2/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/kellyubuntu2/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-02-25_10:11:21
  host      : kellyubuntu2-MS-7A69
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 74052)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html 

This is my current environment：
Linux (Ubuntu) 20.04
Python 3.7.6
PyTorch 1.10.2
CUDA 11.3
GCC 9.3.0
mmcv-full 1.4.5

Any suggestions on how to fix this?
Thank you!
With best regards,
Kelly

**Comment by kkellyk** [comment]
This is my current environment：
Linux (Ubuntu) 20.04
Python 3.7.6
PyTorch 1.10.2
CUDA 11.3 
GCC 9.3.0
mmcv-full 1.4.5

Any suggestions on how to fix this? 
Thank you!
With best regards,
Kelly

**Comment by cliangyu** [comment]
You don't have ImageNet installed in your machine.
Please refer to the documentatoin of mmselfsup/mmclassification about the datasets.

**Comment by kkellyk** [comment]
Thanks for your reply,
So I need to download the ImageNet below, and unzip it, right?
- ILSVRC2012_img_train.tar (~138GB)
- ILSVRC2012_img_val.tar (~6.3GB)

But it will take a while to download, I will ask you again after the download data is over.
Thank you!
With best regards,
Kelly

**Comment by kkellyk** [comment]
> You don't have ImageNet installed in your machine. Please refer to the documentatoin of mmselfsup/mmclassification about the datasets.

Thanks for your reply,
So I need to download the ImageNet below, and unzip it, right?
- ILSVRC2012_img_train.tar (~138GB)
- ILSVRC2012_img_val.tar (~6.3GB)

But it will take a while to download, I will ask you again after the download data is over.
Thank you!
With best regards,
Kelly
