### ISSUE TITLE
How to install mmselfsup on Arm aarch64?

### ISSUE THREAD

**Issue by seifer08ms** [open-mmlab/mmselfsup#226]
Hello! I want to use mmselfsup  on the arm platform. But I failed to install dependencies such as faiss-gpu on aarch64. Is it possible to use mmselfsup for aarch64?

**Comment by fangyixiao18** [comment]
Actually, we haven't tried that before.
You can try this way: https://github.com/open-mmlab/mmselfsup/blob/dev_v0.7.0/mmselfsup/utils/clustering.py#L9

**Comment by fangyixiao18** [comment]
You can check this: https://github.com/open-mmlab/mmselfsup/blob/dev_v0.7.0/mmselfsup/utils/clustering.py#L9
And remove `faiss` from requirements/runtime.txt.
I installed it on Apple M1 chip successfully.

We have already moved `faiss` to requirements/optional.txt in dev-v0.7.0, which will be released in a few days.
