### ISSUE TITLE
Is there any way to use jupyter (python) in window10 to execute code?

### ISSUE THREAD

**Issue by kkellyk** [open-mmlab/mmselfsup#230]
Because I only need to use the Online Deep Clustering model.
Using Jupyter is more in line with my usage habits.
But I don't know how to implement it.

Thank you
Kelly

**Comment by fangyixiao18** [comment]
Sorry for late reply, we don't have related tutorial yet.
Besides, ODC currently doesn't support windows 10 platform.

**Comment by fangyixiao18** [comment]
Hi, now we have colab tutorial for basic usage, it might help.
https://github.com/open-mmlab/mmselfsup/blob/master/demo/mmselfsup_colab_tutorial.ipynb
