### ISSUE TITLE
[Tools] MIM Reconstructed Image Visualization

### ISSUE THREAD

**Issue by cliangyu** [open-mmlab/mmselfsup#242]
**Describe the feature**
We wish to visualize the reconsructed images to evaluate the model performance.

**Motivation**
It is convenient when we can check the reconstructed parts of reconstructed images.

**Related resources**
https://github.com/facebookresearch/mae
https://github.com/pengzhiliang/MAE-pytorch

**Comment by fangyixiao18** [comment]
Hello, thanks for your contribution. 
We have added the tool by ourselves. If you are still interested in supporting some features in mmselfsup,  feel free to contact us! We could discuss the future plans.
