### ISSUE TITLE
How to import mmdet backbones?

### ISSUE THREAD

**Issue by LMerCy** [open-mmlab/mmselfsup#244]
mmdet and mmselfsup use different register BACKBONES, what's the best practice to use BACKBONES of mmdet?

**Comment by LMerCy** [comment]
Can solved by https://github.com/open-mmlab/mmselfsup/pull/239

**Comment by lifuguan** [comment]
你好，我在使用MMDet的DETR模型的时候也出现了同样的问题。我已经阅读了#239但并没有发现解决方案。请问该怎么做呢？十分感谢！

**Comment by LMerCy** [comment]
@lifuguan look at this https://cloud.tencent.com/developer/article/1935911 , briefly just use as:
 ```
custom_imports=dict(imports='mmcls.models', allow_failed_imports=False)
 backbone=dict(
        # use "scope.type" to import module from mmcls
        type='mmcls.MobileNetV3',
        arch='large',
        out_indices=(5, 11, 14),
        init_cfg=dict(
            type='Pretrained',
            checkpoint='mmcls://mobilenet_v3_large'),
        _delete_=True)
```

**Comment by lifuguan** [comment]
@LMerCy Thanks for your quick reply!👍
