### ISSUE TITLE
Training speed is slower in 0.7.1 than 0.6.0

### ISSUE THREAD

**Issue by 4-0-4-notfound** [open-mmlab/mmselfsup#246]
8*V100 envs:
```
env1:  pt181 cu101 mmcv-full 1.4.6 mmdet 2.22 mmcls 0.20.0  mmSelfSup: 0.7.1
env2:  pt181 cu101 mmcv-full 1.4.6 mmdet 2.22 mmcls 0.20.0  mmSelfSup: 0.6.0
env3:  pt181 cu101 mmcv-full 1.4.2 mmdet 2.22 mmcls 0.20.0  mmSelfSup: 0.6.0
```
command:
`GPUS_PER_NODE=8 GPUS=8 bash tools/slurm_train.sh test_part  test configs/selfsup/densecl/densecl_resnet50_8xb32-coslr-200e_in1k.py work_dirs/densecl/densecl_resnet50_8xb32-coslr-200e_in1k`

result: eta:  @ epoch1 1050/5004 iter
env1:  3.5 days
env2:  3 days
env3:  2.8 days

So `mmcv 1.4.2+mmSelfSup 0.6.0`  is significant faster than `mmcv 1.4.6+mmSelfSup 0.7.1`, and `mmSelfSup 0.6.0` is faster than `mmSelfSup 0.7.1`

**Comment by fangyixiao18** [comment]
We will check it.
