### ISSUE TITLE
Support COCO as one of the pretraining dataset as in DenseCL

### ISSUE THREAD

**Issue by 4-0-4-notfound** [open-mmlab/mmselfsup#251]
**Motivation**
MS COCO is becoming one of the most important datasets for pretraining. More and more paper would use is as the pretraining dataset, like DenseCL.

**Related resources**
The DenseCL already has the implementation in OpenSelfSup, so it would be easy to add in mmselfsup.

https://github.com/WXinlong/DenseCL/blob/main/configs/selfsup/densecl/densecl_coco_800ep.py

**Comment by fangyixiao18** [comment]
Thanks for your suggestion, we will consider to add it to our future plan.
Or you can create a PR to support this feature. 
Welcome to become a contributor of MMSelfSup!
