### ISSUE TITLE
Missing keys when load pretrain model

### ISSUE THREAD

**Issue by CyanScholar** [open-mmlab/mmselfsup#255]
![image](https://user-images.githubusercontent.com/62923472/160262468-19a95499-3332-44e0-9d16-7547ce57d164.png)
When I try to train a new model on my custom dataset, and load the pretain model: densecl_resnet50_8xb32-coslr-200e_in1k_20220225-8c7808fe.pth, it shows missing keys.

**Comment by fangyixiao18** [comment]
Because the model we provide is only the extracted backbone weights and we also remove the prefix, such as encoder_q, etc.

**Comment by CyanScholar** [comment]
I found that there are many cases when loading models will have such problems, how can I solve them?

**Comment by fangyixiao18** [comment]
> I found that there are many cases when loading models will have such problems, how can I solve them?

Currently, you can modify the key of the weight file for encoder_q and encoder_k in DenseCL, but it only has the backbone weights (no neck weights, no queue information). 
Maybe we will consider to provide the original checkpoint in the future.

**Comment by Mxbonn** [comment]
> > I found that there are many cases when loading models will have such problems, how can I solve them?
> 
> Currently, you can modify the key of the weight file for encoder_q and encoder_k in DenseCL, but it only has the backbone weights (no neck weights, no queue information). Maybe we will consider to provide the original checkpoint in the future.

Any updates on this? It would make sense to release the entire models instead of only the extracted backbones. Frankly I even see little use in only providing the backbone.

**Comment by fangyixiao18** [comment]
> Any updates on this? It would make sense to release the entire models instead of only the extracted backbones. Frankly I even see little use in only providing the backbone.

Thanks for your suggestion, if all goes well, we will release the entire models in 2 months.
