### ISSUE TITLE
Training speed benchmark

### ISSUE THREAD

**Issue by xvjiarui** [open-mmlab/mmselfsup#27]
Hi @XiaohangZhan 
It would be nice to provide a training speed benchmark for these methods. 
It doesn't have to be the actual total training time (sometimes training is interrupted I know). Maybe just a seconds/epoch comparison will be a good illustration on the speed of each method.  
Many thx!

**Comment by Jiahao000** [comment]
See [MODEL_ZOO.md](https://github.com/open-mmlab/OpenSelfSup/blob/master/docs/MODEL_ZOO.md#pre-trained-model-download-links). The training speed is for reference only since different methods use different batch size.
