### ISSUE TITLE
Shared4Conv1FCBBoxHead or Shared2FCBBoxHead in COCO detection?

### ISSUE THREAD

**Issue by liming-ai** [open-mmlab/mmselfsup#274]
I noticed that the default Mask RCNN setting in detectron2 and mmdet is `Shared2FCBBoxHead` for `bbox_head`. However, `Shared4Conv1FCBBoxHead` is used to evaluate coco under mmselfsup config.

**Comment by fangyixiao18** [comment]
Thanks for your reporting, we will check our benchmark in next month.
