### ISSUE TITLE
Unexpected memory occupied in gpu:0 when using multi-gpu training

### ISSUE THREAD

**Issue by lifuguan** [open-mmlab/mmselfsup#275]
I'm using multi-gpus training on my 8*2080ti machine. However, gpu:0 occupied much more memories than other GPUs, which makes me very uncomfortable. Are there any solutions to reduce the memory usage in GPU:0? (By the way, it doesn't happen in mmdet as well as other mm toolbox.)
## Using Command
```bash
export CUDA_VISIBLE_DEVICES=1,2,3,4,5
export PYTHONPATH=$PWD:$PYTHONPATH  
./tools_selfsup/dist_train.sh configs/selfsup/upknet/oursnet_s3_r50_fpn_1x_coco.py 5
```
## Screenshots
<img width="910" alt="image" src="https://user-images.githubusercontent.com/17793134/162436835-47eba99e-75ad-4256-87dd-2bbf78f898c0.png">

**Comment by YuanLiuuuuuu** [comment]
Before you run downstream tasks, you should use this [script](https://github.com/open-mmlab/mmselfsup/blob/master/tools/model_converters/extract_backbone_weights.py) to convert your checkpoints.

**Comment by lifuguan** [comment]
I'm pretraining my model right now, so there is no checkpoint in this procedure.

**Comment by YuanLiuuuuuu** [comment]
Could you please discribe your problems in detail?

**Comment by YuanLiuuuuuu** [comment]
This issue will be closed, if you do not have any further response. But feel free to reopen it, if needed.
