### ISSUE TITLE
wrong batchsize showed in file name

### ISSUE THREAD

**Issue by luuuyi** [open-mmlab/mmselfsup#279]
in mae method's config dir, every config's name contains *8xb512*, and in relate py file this config is added: 
https://github.com/open-mmlab/mmselfsup/blob/df907e5ce02951e68e5de825986d8d7e879ac5b4/configs/selfsup/mae/mae_vit-base-p16_8xb512-coslr-400e_in1k.py#L9

Actually, imgs_per_gpu parameter is deprecated, we should approve samples_per_gpu, but the logic in here is wrong:
https://github.com/open-mmlab/mmselfsup/blob/df907e5ce02951e68e5de825986d8d7e879ac5b4/mmselfsup/apis/train.py#L91

when `imgs_per_gpu=128`  is added in configs/selfsup/_bae_/datasets/imagenet_mae.py, samples_per_gpu will be assigned by imgs_per_gpu, means `samples_per_gpu=128`. So the actual value in all training program is samples_per_gpu=128, batchsize is 8x128.

**Comment by fangyixiao18** [comment]
We have created a PR to use `samples_per_gpu` in config.
Please refer to https://github.com/open-mmlab/mmselfsup/pull/278

**Comment by luuuyi** [comment]
@fangyixiao18 ok, i see it. Maybe the cfg file name in mae should also change to 8x128. Anyway, nice work.
