### ISSUE TITLE
SimMIM error

### ISSUE THREAD

**Issue by Margrate** [open-mmlab/mmselfsup#285]
**config file**

file "configs/selfsup/simmim/simmim_swin-base_16xb128-coslr-100e_in1k.py" does not exist

**self.patch_embed**
File "mmselfsup/models/backbones/simmim_swin.py", in forward
    x, hw_shape = self.patch_embed(x)
ValueError: too many values to unpack (expected 2)

**Comment by YuanLiuuuuuu** [comment]
Please upgrade `mmcls` to >= `0.21.0`

**Comment by Margrate** [comment]
> Please upgrade `mmcls` to >= `0.21.0`

Thank you for your reply. It works
