### ISSUE TITLE
Cannot find a backbone module in the checkpoint.

### ISSUE THREAD

**Issue by HuXinzhi1004** [open-mmlab/mmselfsup#286]
I download the pretrained model from model_zoo.
![image](https://user-images.githubusercontent.com/75877054/164189714-e020efd3-857e-4baf-bc5c-2440219f2fd9.png)
 Then I run 
`python ./tools/model_converters/extract_backbone_weights.py {CHECKPOINT} {MODEL_FILE}`
to extract the  backbone weight , but I got wrong:
![image](https://user-images.githubusercontent.com/75877054/164190042-54d5d8a5-f224-43f6-83c5-dc40507327a0.png)
I wonder why？

**Comment by fangyixiao18** [comment]
The downloaded models have been extracted, you can use them directly.
