### ISSUE TITLE
Does mmselfsup can be used to self supervised images of text to then evaluate on mmocr downstreams tasks?

### ISSUE THREAD

**Issue by ykacer** [open-mmlab/mmselfsup#292]
i'm working on mmocr but I'm very new to mmselfsup.
Is it possible to use mmselfsup with my images of text and then use the backbone to train a mmocr model?
Thanks

**Comment by fangyixiao18** [comment]
Yes, it is possible to do so. However, currently the experiments of self supervised learning pretraining are done on ImageNet, which is a object-centric dataset and is different with images of text, so I guess dense contrastive learning methods (DenseCL) or masked image modeling methods (MAE, SimMIM) are more appropriate.
