### ISSUE TITLE
[Feature] DALI support

### ISSUE THREAD

**Issue by liming-ai** [open-mmlab/mmselfsup#293]
@YuanLiuuuuuu @Jiahao000 @fangyixiao18 

**DALI data transforms**

**Motivation**
We need DALI for processing data transforms faster.

**Related resources**
Please refer to [this repo](https://github.com/alibaba/EasyCV/blob/master/easycv/datasets/shared/dali_tfrecord_multi_view.py), which is implemented based on mmselfsup and support DALI

**Comment by fangyixiao18** [comment]
Thanks for your advice, we will consider and discuss it.
