### ISSUE TITLE
Are there any tutorials for self-supervised training of yolov5 detection models?

### ISSUE THREAD

**Issue by APeiZou** [open-mmlab/mmselfsup#298]
**Checklist**

Are there any tutorials for self-supervised training of yolov5 detection models?@open-mmlab

**Comment by APeiZou** [comment]
@XiaohangZhan   hello,  Are there any tutorials for self-supervised training of yolov5 detection models?

**Comment by fangyixiao18** [comment]
Hello, thanks for your reporting. What did you mean ' yolov5 detection models '? Did you mean backbone？

**Comment by APeiZou** [comment]
@fangyixiao18      Are there any tutorials for self-supervised training of detection models?

**Comment by fangyixiao18** [comment]
You can train your backbone models and load them in downstream tasks.
