### ISSUE TITLE
ODC

### ISSUE THREAD

**Issue by ghost** [open-mmlab/mmselfsup#302]
Hi, is it possible to use ODC with only one CPU/GPU ? I tried to do the "mmselfsup_colab_tutorial" but I had this error: 
![image](https://user-images.githubusercontent.com/92847020/166230682-b6888b82-a43d-4ee3-ab2d-79478606687e.png)
Will it be the same with ODC?

Thanks for the help

**Comment by fangyixiao18** [comment]
ODC is not supported with only one CPU/GPU.
Besides we don't recommend to run self supervised algorithms with only one CPU/GPU as these algorithms need long time to converge generally.

**Comment by ghost** [comment]
Thanks for the answer @fangyixiao18
