### ISSUE TITLE
Implement MICLe

### ISSUE THREAD

**Issue by fcakyon** [open-mmlab/mmselfsup#316]
Paper name: Big Self-Supervised Models Advance Medical Image Classification
Affiliation: Google Research and Health
Year: 2021
Citations: 74

+3.6 top1 accuracy improvement over SimCLR

**Comment by fangyixiao18** [comment]
Thanks for your suggestion, we will check it later.

**Comment by ys-zong** [comment]
> Paper name: Big Self-Supervised Models Advance Medical Image Classification Affiliation: Google Research and Health Year: 2021 Citations: 74
> 
> +3.6 top1 accuracy improvement over SimCLR

+1

**Comment by fcakyon** [comment]
@fangyixiao18 it is not completed, why did you close it?

**Comment by fangyixiao18** [comment]
We have added it to our backlog, feel free to reopen it if you think it is needed.
