### ISSUE TITLE
How to use Mae forward propagation to reconstruct pixels? 

### ISSUE THREAD

**Issue by joeyslv** [open-mmlab/mmselfsup#320]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the FAQ documentation but cannot get the expected help.

**Comment by YuanLiuuuuuu** [comment]
MAE uses this [func](https://github.com/open-mmlab/mmselfsup/blob/399b5a0d6e638328c8622e4696b09a5a30b8b8dc/mmselfsup/models/backbones/mae_vit.py#L106) to generate mask and use this [line](https://github.com/open-mmlab/mmselfsup/blob/399b5a0d6e638328c8622e4696b09a5a30b8b8dc/mmselfsup/models/heads/mae_head.py#L45) to compute the reconstruction loss.
