### ISSUE TITLE
SimCLR non-dist support?

### ISSUE THREAD

**Issue by erceguder** [open-mmlab/mmselfsup#324]
Hi,

Is there anyway to make SimCLR work on a single GPU instance?

Thanks in advance

**Comment by fangyixiao18** [comment]
Currently, we don't support single GPU training officially, you could revise code by yourself to remove distributed operation.

**Comment by erceguder** [comment]
@fangyixiao18 Thank you, which components of MMSelfSup should I revise other than the configuration file?

**Comment by fangyixiao18** [comment]
> @fangyixiao18 Thank you, which components of MMSelfSup should I revise other than the configuration file?

There is a `GatherLayer` operation in simclr algorithm, you can check it.
