### ISSUE TITLE
Documentation website language error？

### ISSUE THREAD

**Issue by nuaalyh** [open-mmlab/mmselfsup#325]
https://mmselfsup.readthedocs.io/zh_CN/latest/
I chose Chinese, but English is still displayed. Is it a setting error?

**Comment by fangyixiao18** [comment]
Thanks for your reporting, we will check it ASAP.

**Comment by YuanLiuuuuuu** [comment]
> https://mmselfsup.readthedocs.io/zh_CN/latest/ I chose Chinese, but English is still displayed. Is it a setting error?

Bug has been fixed. Feel free to reopen this issue, if you have any other problems.
