### ISSUE TITLE
How to reduce memory size

### ISSUE THREAD

**Issue by erceguder** [open-mmlab/mmselfsup#331]
Hi,

I will try to give as much details as possible.

Currently I've been trying to run SimCLR with a U-Net backbone (of MMSegmentation) on a multi-GPU instance. I've set all the modules, added required files etc. e.g. [base simclr config](https://github.com/open-mmlab/mmselfsup/blob/master/configs/selfsup/_base_/models/simclr.py) is replaced with a UNet backbone. The output of the backbone is of size (64x224x224) (_for a single image_). Setting [in_channels](https://github.com/open-mmlab/mmselfsup/blob/86290150d853fe817e1335a5aad90f1515b36fb0/configs/selfsup/_base_/models/simclr.py#L13) of neck to 64x224x224 (= 3211264) results in the error below. From simple calculations (64x224x224x8 / (1024x1024) = 24.5GB) it seems that floating point numbers take up 8 bytes in the GPU.

I've tried `mmcv.runner.fp16_utils.wrap_fp16_model` yet nothing changed. How can I reduce memory size on GPU?

Thanks in advance

> RuntimeErrorRuntimeError: : CUDA out of memory. Tried to allocate 24.50 GiB (GPU 1; 22.20 GiB total capacity; 110.50 MiB already allocated; 20.58 GiB free; 116.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONFCUDA out of memory. Tried to allocate 24.50 GiB (GPU 2; 22.20 GiB total capacity; 110.50 MiB already allocated; 20.58 GiB free; 116.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by fangyixiao18** [comment]
As for reducing memory usage, maybe you can try these methods:

- reduce the size of the image, the `H` or `W`, or the channel number.
- reduce the `in_channel` of the neck, 3211264 is too large for FC layer and add some pooling operation before the non-linear neck.
- reduce the batch size and use gradient acculmulate.

You can try this method above.
