### ISSUE TITLE
how to update the installed mmselfsup to the newest version

### ISSUE THREAD

**Issue by Yoooss** [open-mmlab/mmselfsup#334]
I noticed that the version of mmselfsup I used is v0.8.0, and the newest version is v0.9.1. 
Could I use the command " pip update mmselfsup" to update? And if the version is updated, will other dependency such as mmcv need to change to other version too?
I'm afraid that when I try to update the version, the version that I'm using couldn't run successfully anymore.

**Comment by YuanLiuuuuuu** [comment]
You can refer to [FAQ](https://github.com/open-mmlab/mmselfsup/blob/master/docs/en/faq.md) for the dependencies of MMSelfSup w.r.t each version. Thanks!

**Comment by Yoooss** [comment]
So can I use the command "pip update mmselfsup" to update to the newest version directly？And then refer to FAQ to check the version of the denpendecies.
Thanks for your help.

**Comment by Yoooss** [comment]
And I  want to ask how do I train with my own data. I already change the data into the VOC format. However, I don't know how to change the class name 
![2022-06-23 23-30-01 的屏幕截图](https://user-images.githubusercontent.com/49121651/175337233-0495f8fe-78d5-4fd6-a23e-be23e99d1884.png)
The class name of my own data is different, such as 货船，航母 and so on.
But I didn't find where  to modify the code referring to the csdn blog as below.
![2022-06-23 23-33-06 的屏幕截图](https://user-images.githubusercontent.com/49121651/175337826-f4028bf1-ebb1-4c72-8b3e-28af94a30ffa.png)

**Comment by Yoooss** [comment]
I also tried to modified the file "mmselfsup/datasets/data_sources/base.py" as below.
![2022-06-24 10-28-05 的屏幕截图](https://user-images.githubusercontent.com/49121651/175450087-bcb7b376-8bc7-4dee-b475-2526d0015a5a.png)
And modified the num_classes into 33 according to my dataset as below.
![2022-06-24 10-28-54 的屏幕截图](https://user-images.githubusercontent.com/49121651/175450163-be3125d5-225a-4518-a766-8f45150f86c4.png)

However it still doesn't work. T.T
 
![2022-06-24 10-29-52 的屏幕截图](https://user-images.githubusercontent.com/49121651/175450296-68f2f527-fc1c-4e22-acc3-fb11a21c07c1.png)

**Comment by Yoooss** [comment]
And now it raised that this error ,I don't know how to solve.
![2022-06-24 12-00-38 的屏幕截图](https://user-images.githubusercontent.com/49121651/175459964-ccbecac1-bb3b-453f-98dc-9f218215301c.png)
the command is "bash tools/benchmarks/mmdetection/mim_dist_train_c4.sh configs/benchmarks/mmdetection/voc0712/faster_rcnn_r50_c4_mstrain_2x_voc0712.py checkpoints/simclr_resnet50_8xb32-coslr-200e_in1k_20220428-46ef6bb9.pth 1"

**Comment by YuanLiuuuuuu** [comment]
> So can I use the command "pip update mmselfsup" to update to the newest version directly？And then refer to FAQ to check the version of the denpendecies. Thanks for your help.

You can use ``pip install mmselfsup --upgrade`` and all these dependecies will be installed automatically.

**Comment by YuanLiuuuuuu** [comment]
> And now it raised that this error ,I don't know how to solve. ![2022-06-24 12-00-38 的屏幕截图](https://user-images.githubusercontent.com/49121651/175459964-ccbecac1-bb3b-453f-98dc-9f218215301c.png) the command is "bash tools/benchmarks/mmdetection/mim_dist_train_c4.sh configs/benchmarks/mmdetection/voc0712/faster_rcnn_r50_c4_mstrain_2x_voc0712.py checkpoints/simclr_resnet50_8xb32-coslr-200e_in1k_20220428-46ef6bb9.pth 1"

So you want to evaluate the pretrained model on detection task ?

**Comment by Yoooss** [comment]
Yes. I want to evaluate on my own dataset on object detection

**Comment by YuanLiuuuuuu** [comment]
> Yes. I want to evaluate on my own dataset on object detection

Since ``MMSelfSup`` use ``MMDetection`` for evaluation, all these training recipes are in ``MMDetection``. If you want to load your customized dataset, you should reformat your dataset into the format required by ``MMDetection``. You can refer to this [doc](https://github.com/open-mmlab/mmdetection/blob/master/docs/en/tutorials/customize_dataset.md). Thanks!

**Comment by Yoooss** [comment]
As I wrote above. I have already change my dataset to VOC format. And change the num_classes according to mydataset . 
But it still raised the error.

**Comment by YuanLiuuuuuu** [comment]
> > And now it raised that this error ,I don't know how to solve. ![2022-06-24 12-00-38 的屏幕截图](https://user-images.githubusercontent.com/49121651/175459964-ccbecac1-bb3b-453f-98dc-9f218215301c.png) the command is "bash tools/benchmarks/mmdetection/mim_dist_train_c4.sh configs/benchmarks/mmdetection/voc0712/faster_rcnn_r50_c4_mstrain_2x_voc0712.py checkpoints/simclr_resnet50_8xb32-coslr-200e_in1k_20220428-46ef6bb9.pth 1"
> 
> So you want to evaluate the pretrained model on detection task ?

Since you load the pre-trained model provided by ``MMSelfSup`` , some keys are not matched exactly, just as shown in the error. One of the workaround is to set ``strict`` to ``False`` when you load the pre-trained model.

**Comment by Yoooss** [comment]
Sorry to interrupt you again.
Why I recover the file to the original content, but still got this error? Now the code is totally the same with before.
Before I could run successfully on the VOC dataset and get the result as below.
![2022-06-24 20-54-31 的屏幕截图](https://user-images.githubusercontent.com/49121651/175540329-b67be6cc-8574-44bf-b9f3-11503ba62a50.png)

But now I got the result that:
![2022-06-24 21-00-03 的屏幕截图](https://user-images.githubusercontent.com/49121651/175541141-d26175c4-42e7-4843-9678-f8eb1802637d.png)

![2022-06-24 20-57-05 的屏幕截图](https://user-images.githubusercontent.com/49121651/175540564-c331ba17-bcdb-46c2-82a3-0655cfb303de.png)

Both tests were based on the same command 
"bash tools/benchmarks/mmdetection/mim_dist_train_c4.sh configs/benchmarks/mmdetection/voc0712/faster_rcnn_r50_c4_mstrain_2x_voc0712.py checkpoints/simclr_resnet50_8xb32-coslr-200e_in1k_20220428-46ef6bb9.pth 1".
 Thanks for your help.

**Comment by YuanLiuuuuuu** [comment]
This issue will be closed. If you have any other problems, please feel free to reopen it.
