### ISSUE TITLE
reproduce results and pre-trained models

### ISSUE THREAD

**Issue by guochengqian** [open-mmlab/mmselfsup#34]
Hello OpenSelfSup team, 
Thank you for open-sourcing the amazing tool for SSL. 
In the [Model_Zoo](https://github.com/open-mmlab/OpenSelfSup/blob/master/docs/MODEL_ZOO.md#imagenet-linear-classification), you report the Top-1 acc for many methods.  I wana know how to reproduce them? Are the using the exact same parameters you provide in the config file?  
I find some parameters conflict with the setting you mentioned in the Readme file. 
For example, what's the training epochs to be used in the linear classification experiment? 100 or 200? in the config, it says 100 but in your readme, you mention most of the experiments use 200. 

Another question, will you kindly release the pretrained model of the second stage (training on imagenet with the frozen feature)?
For now, you provide with the pretrained models of the first stage (self-supervised training). Really appreciate that.   

Thank you !!

**Comment by guochengqian** [comment]
I have trained relative_loc exp followed the readme file. and I obtain similar result already (30.03, slighter worse than your reported 30.83). 
The only difference is that I use 4 GPUs instead of 8.
I want to know the reason why I get 0.8 worse result? do you think it is because of the number of GPUs or the training epochs should be 200 instead of 100?

Thank you for your help. Thanks again for your reproducible code.

**Comment by XiaohangZhan** [comment]
1. 200 epochs for pretrain, 100 for linear classification eval.
2. Releasing linear classification is meaningless since they are for eval. Since the pretrained models are released. You can easily evaluate the petrained models on ImageNet following GETTING_STARTED.md
3. You should use 8 GPUs and exactly follow the config to reproduce the number.

**Comment by guochengqian** [comment]
Great! Thank you!
