### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by cnnAndBn** [open-mmlab/mmselfsup#342]
hi
  in version 0.8
 https://github.com/open-mmlab/mmselfsup/blob/df907e5ce02951e68e5de825986d8d7e879ac5b4/mmselfsup/datasets/data_sources/base.py#L113-L116
 are these lines redundant?

**Comment by YuanLiuuuuuu** [comment]
Thank you for pointing out this redundancy. line#113 to line#115 is redundant, but #line116. We will fix it in our upcoming release.

**Comment by YuanLiuuuuuu** [comment]
This issue will be closed. If you have any further problems, feel free to reopen it. Thanks!
