### ISSUE TITLE
Lr_config list out-of-date

### ISSUE THREAD

**Issue by doem97** [open-mmlab/mmselfsup#351]
Hi contributors,

The below ref link is out-of-date. I suggest updating to mmselfsup main repo rather than from a blob. Thanks.
https://github.com/open-mmlab/mmselfsup/blob/381fd9ad38f6bc22b2867e41ee37e5988b95ea6c/docs/en/tutorials/4_schedule.md?plain=1#L53

**Comment by fangyixiao18** [comment]
Thanks for your reporting. It's our mistake and we will check it carefully in the future.
Here is the master branch link: https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/lr_updater.py
Besides, are you willing to create a PR to help us correct it？Thanks.

**Comment by doem97** [comment]
> Thanks for your reporting. It's our mistake and we will check it carefully in the future. Here is the master branch link: https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/lr_updater.py Besides, are you willing to create a PR to help us correct it？Thanks.

OK, I updated it. Thanks.
