### ISSUE TITLE
Dump the training configuration file to work directory. 

### ISSUE THREAD

**Issue by foolhard** [open-mmlab/mmselfsup#400]
**Describe the feature**

Dump the final training configuration file to work directory. It'll be easy for users to track the config of the training after started. 

**Motivation**

 It is inconvenient when **we want to track the configuration file after training started.**

**Related resources**

This is supported in mmdetetion. Below is ref. code. 
.
```
    # dump config
    cfg.dump(osp.join(cfg.work_dir, osp.basename(args.config)))
```

**Comment by fangyixiao18** [comment]
Hi, thanks for your valuable suggestion. 
Are you willing to create a PR to help us add it? Thanks in advance!
