### ISSUE TITLE
DenseCL weight initialization inconsistent with original code.

### ISSUE THREAD

**Issue by lorinczszabolcs** [open-mmlab/mmselfsup#404]
**Checklist**

1. I have searched related issues but cannot get the expected help. ✅
2. I have read the FAQ documentation but cannot get the expected help. ✅

Hi!

I noticed, that the weight initialization in DenseCL is inconsistent with the original code, namely that when pre-trained weights are loaded, only the query encoder will get initialized, but the weights won't be copied to the key encoder, while in the original repo it is done like that, see 
https://github.com/WXinlong/DenseCL/blob/360df04ba25aca36d42e85c5a96552783568fccf/openselfsup/models/densecl.py#L36
and
https://github.com/WXinlong/DenseCL/blob/360df04ba25aca36d42e85c5a96552783568fccf/openselfsup/models/densecl.py#L51-L58.

I think DenseCL's `init_weights` should be overrided by having
```python
def init_weights(self):
    """Init weights and copy query encoder init weights to key encoder."""
    super().init_weights()
    for param_q, param_k in zip(self.encoder_q.parameters(),
                                self.encoder_k.parameters()):
        param_k.data.copy_(param_q.data)
        param_k.requires_grad = False
```

**Comment by YuanLiuuuuuu** [comment]
There is no need to overwirte the ``init_weights`` in DenseCL, for both the query encoder and key encoder will be initialized with the pretrained weights. Thanks!

**Comment by YuanLiuuuuuu** [comment]
One of the corner case is that you do not save the weights of the key encoder, which may result in the problem you discuss above. But MMSelfSup will save both the query and key encoder automatically.

**Comment by lorinczszabolcs** [comment]
> There is no need to overwirte the `init_weights` in DenseCL, for both the query encoder and key encoder will be initialized with the pretrained weights. Thanks!

For me the log showed that ` encoder_k[0]` weights are the same before initialization and after, and that’s why I assumed it might have been left out from initialization. As for encoder_q[0], that was initialized correctly, so that’s why I assumed the copy isn’t taking place.

Edit: what I’m trying to do is to load pretrained weights into the backbone that were pre-trained on ImageNet, before running the DenseCL pre-training.

**Comment by YuanLiuuuuuu** [comment]
> > There is no need to overwirte the `init_weights` in DenseCL, for both the query encoder and key encoder will be initialized with the pretrained weights. Thanks!
> 
> For me the log showed that ` encoder_k[0]` weights are the same before initialization and after, and that’s why I assumed it might have been left out from initialization. As for encoder_q[0], that was initialized correctly, so that’s why I assumed the copy isn’t taking place.
> 
> Edit: what I’m trying to do is to load pretrained weights into the backbone that were pre-trained on ImageNet, before running the DenseCL pre-training.

Yes, you are right. That's the corner case I discribed above.
