### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by ander002** [open-mmlab/mmselfsup#416]
# TypeError: cannot unpack non-iterable NoneType object

When i run the jupyter demo about mae_Visualization, The Error appear,just like the title,what shuld i do ?

**Comment by fangyixiao18** [comment]
Can you provide more detailed information? Which command did you run when this error occurs?

**Comment by ander002** [comment]
Thanks,i have solved it and realized the visualization of SimMIM,can i upload some code?

**Comment by fangyixiao18** [comment]
> Thanks,i have solved it and realized the visualization of SimMIM,can i upload some code?

Of course, welcome to create a PR! Thanks
