### ISSUE TITLE
How to eval deepcluster

### ISSUE THREAD

**Issue by jyang68sh** [open-mmlab/mmselfsup#441]
Hi, Thanks for the great framework.

I am new to the framework. I have trained a deepcluster model. 

When I want to test it, it gives an error: "AttributeError: 'ConfigDict' object has no attribute 'val'"

When I want to benchmark it, it gives an error: "AttributeError: 'ConfigDict' object has no attribute 'log_level'"

I am confused on how to check the result. Thanks!

**Comment by jyang68sh** [comment]
@cclauss @c-liangyu Please have a look. Thanks!

**Comment by fangyixiao18** [comment]
Sorry for the late reply, could your provide more detailed information? What is your command and What is your config file?

**Comment by jyang68sh** [comment]
@fangyixiao18 Thanks. I solved the issue. Great framework btw
