### ISSUE TITLE
Could you provide some examples of dataset setup?

### ISSUE THREAD

**Issue by drmeerkat** [open-mmlab/mmselfsup#45]
Hi guys, thanks for the great work. I am trying to build upon your ODC network but I found it convoluted to understand the code structure. If I just want to retrain the odc network, how should I set up my environment to run the bash file?

For example, what is `data_train_list` and `data_train_root`?

**Comment by drmeerkat** [comment]
And `memcached`, `mclient_path`?

**Comment by XiaohangZhan** [comment]
Just follow the GETTING_STARTED.md. data_train_root is your imagenet root, data_train_list is the training list. They are described in INSTALL.md. memcached is set as False if you don't have it.
