### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'test'

### ISSUE THREAD

**Issue by tuntianjun** [open-mmlab/mmselfsup#482]
**here is my test code for inference:**
![image](https://user-images.githubusercontent.com/67778333/189856064-cc934d8f-d13c-4b75-aedb-e09648524c61.png)

**the error:**
![image](https://user-images.githubusercontent.com/67778333/189854375-cc9cbb5b-a034-42cd-acf5-16c91e1c7528.png)

**what does this error mean?**

**Comment by fangyixiao18** [comment]
It is because your config file doesn't have the key 'test', you could check it in config file.
Which config did you use?

**Comment by tuntianjun** [comment]
**Thanks, I know the problem. I forgot to change the original config file.**
