### ISSUE TITLE
error after running for 3 epoch , ERROR:torch.distributed.elastic.multiprocessing.api:failed

### ISSUE THREAD

**Issue by alaa-shubbak** [open-mmlab/mmselfsup#505]
Thanks for reporting the unexpected results and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help. yes
2. The unexpected results still exist in the latest version.
no results 
**Describe the Issue**
A clear and concise description of what the bug is, including what results are expected and what the real results you got.

**Reproduction**

1. What command, code, or script did you run?
I am try to train a model for object detection , I used a pretrained model of simclr as a self-supervised approach. 

```bash
bash tools/benchmarks/mmdetection/mim_dist_train_fpn.sh configs/benchmarks/mmdetection/coco/faster_rcnn_r50_c4_mstrain_2x_coco_new.py checkpoints/simclr_resnet50_imagenet.pth 1
```
I used one gpu for the training , and I did not find the python file (mim_dist_train.sh) which  mentioned in your document about running a training for downstream task 
2. Did you make any modifications on the code? Did you understand what you have modified?
yes, I used my custom dataset which has similar format of coco dataset. 
i used to train model with it in mmdetection environment. 
**Environment**

1. Please run `python -c "from mmselfsup.utils import collect_env; print(collect_env())"` to collect necessary environment information and paste it here.

![environment in selfsup](https://user-images.githubusercontent.com/10245810/194414300-eaa855fc-26aa-479b-9617-27c4de11aa70.jpg)

2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
          I install it by create a python environment.
 i used this command :

`
source open_env/bin/activate

git clone https://github.com/open-mmlab/mmselfsup.git
cd mmselfsup
pip install -v -e .
`
I already install the mmdetection, mmcv and all other dependance at same environment. 

   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
   
![config error selfsup](https://user-images.githubusercontent.com/10245810/194413074-009dc3e9-1785-48a5-84e1-55c13ce12352.jpg)

**Error traceback**
If applicable, paste the error traceback here.

```none
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 24194) of binary: /home/shubbak/open_env/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
```
for more detailed find the attached picture 
![selfsupervised learning mm error](https://user-images.githubusercontent.com/10245810/194412206-829fa576-bc52-4452-a4d5-07dc99dff49c.jpg)

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by alaa-shubbak** [comment]
hello , my model is running in the train mode untill epoch 24 , which is very good so far. 

but i have some new error appears as well as some questions as bellow : 
1. the new error : 
after finishing the complete training for the downstream task, i used the optimal epoch for test part on my custom dataset, which has same format to coco and already the downstream was trained on. 
I got such error massage , after using the `_tools/test.py_` function. 

the new error is `KeyError: 'CocoDataset is not in the dataset registry'`

although the training was on this dataset (CocoDataset) ,and this error massage was not presented during the training. 

2. after did the training on downstream task (object detection in my case) , i used to find the optimal epoch using curves and this function ` tools/analysis_tools/analyze_logs.py plot_curve`  , it gives me some info about mAP -bbox . 
this was not happened as the json file created after training did not contain such info .  what shall i do ? if i want to have such info as I  am more concerned about object detection downstream task. 
I will be so grateful if you can help and answer my questions.

**Comment by fangyixiao18** [comment]
> hello , my model is running in the train mode untill epoch 24 , which is very good so far.
> 
> but i have some new error appears as well as some questions as bellow :
> 
> 1. the new error :
>    after finishing the complete training for the downstream task, i used the optimal epoch for test part on my custom dataset, which has same format to coco and already the downstream was trained on.
>    I got such error massage , after using the `_tools/test.py_` function.
> 
> the new error is `KeyError: 'CocoDataset is not in the dataset registry'`
> 
> although the training was on this dataset (CocoDataset) ,and this error massage was not presented during the training.
> 
> 2. after did the training on downstream task (object detection in my case) , i used to find the optimal epoch using curves and this function ` tools/analysis_tools/analyze_logs.py plot_curve`  , it gives me some info about mAP -bbox .
>    this was not happened as the json file created after training did not contain such info .  what shall i do ? if i want to have such info as I  am more concerned about object detection downstream task.
>    I will be so grateful if you can help and answer my questions.

Sorry for late reply. 

1. About your first question, what is your command to run `test.py`?

2. Our `analyze_logs.py` doesn't support to plot mAP-bbox, we will improve it. Currently, you could refer to this [file](https://github.com/open-mmlab/mmdetection/blob/master/tools/analysis_tools/analyze_logs.py) and you could fine some documents [here](https://github.com/open-mmlab/mmdetection/blob/master/docs/en/useful_tools.md)

**Comment by alaa-shubbak** [comment]
Hello , 
Thank you very much for replying. 

for the _1st question_ , i run the function `tools/test.py` within this [repository](https://github.com/open-mmlab/mmselfsup/blob/master/tools/test.py)

for the _2nd question_, I noticed that the produced `log.json` file that comes after training the downstram did not contain mAP_bbox info, it is only contains losses and acc info 

see here an image for that:
![epoch test](https://user-images.githubusercontent.com/10245810/195056987-5ea37298-3501-4b85-82c4-34b8c5034a27.jpg)

for example , epoch 16 did not record any info about mAP , so i think the function `tools/analysis_tools/analyze_logs.py` in both repository (mmdet and mmselsup ) will not work. 

even though , i ran it with mmdetection repository , and I got this error message as expected. 

![error in log running](https://user-images.githubusercontent.com/10245810/195101524-aa185bae-6c93-4a62-be4b-2ef1aa9b17e9.jpg)

in such situation , what shall I do?

**Comment by fangyixiao18** [comment]
Hi, 

For the 1st question, it is because that you run the `test.py` in MMSelfSup repo, but the `CocoDataset` is registered in MMDet. You can try: 1) using `mim test mmdet xxxxx`, there are some tutorial [here](https://github.com/open-mmlab/mim), or using [scripts](https://github.com/open-mmlab/mmdetection/blob/master/tools/test.py) of MMDet directly.

For the 2nd question, we didn't record the mAP-bbox of training process, or you can plot it of the validation process. But from your error message it seems that you didn't run validate in your training process. You can check your log, does it have `val` mode line like below?
![image](https://user-images.githubusercontent.com/36138628/195239978-11d4c14e-5764-449e-a19c-574564c785cf.png)
[log from mmdet](https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_caffe_fpn_1x_coco/faster_rcnn_r50_caffe_fpn_1x_coco_20200504_180032.log.json)

**Comment by alaa-shubbak** [comment]
> k your log, does it have `val` mode

yes , my log.json file does not contain validation process , what do you suggest to have such values ? 

should i take the results from pre-train as a checkpoint  and run the downstream task in mmdetection env with a training tool there ? 

because when running the downstream training script of benchmark [here](https://github.com/open-mmlab/mmselfsup/blob/master/tools/benchmarks/mmdetection/mim_dist_train_fpn.sh) , this did not record or analysis any of validation process .

**Comment by fangyixiao18** [comment]
Could you please provide your full config? you could copy-paste here, thx

**Comment by alaa-shubbak** [comment]
here it is 
![part1](https://user-images.githubusercontent.com/10245810/195817143-ed2a4dee-4583-4809-9ad1-723743d14a0b.jpg)
![part2](https://user-images.githubusercontent.com/10245810/195817151-88b83aa2-77bf-443f-b610-518c3442f6ef.jpg)
![part3](https://user-images.githubusercontent.com/10245810/195817152-077d570d-3668-4cc9-acc2-bbe21212354d.jpg)
![part4](https://user-images.githubusercontent.com/10245810/195817155-076ae8b5-2adc-4352-8981-4b980259986d.jpg)
![part5](https://user-images.githubusercontent.com/10245810/195817158-097083c3-5df1-443c-80c9-858bb37b867a.jpg)
![part6](https://user-images.githubusercontent.com/10245810/195817161-10cfec5a-99eb-431a-8912-6e02b31c70ed.jpg)

**Comment by fangyixiao18** [comment]
You are using `EpochBasedRunner`, so the interval here is supposed to be 1.
![image](https://user-images.githubusercontent.com/36138628/195963536-8a209d93-2b1a-4eb4-871d-d422bcca2d6a.png)

you could change the interval and train again to see whether it has val mAP in the log

**Comment by fangyixiao18** [comment]
Due to the inactivity of the issue, we will close it. Feel free to open a new one if you have other questions.
