### ISSUE TITLE
[Bug] URL invalid in benchmark config

### ISSUE THREAD

**Issue by tonysy** [open-mmlab/mmselfsup#521]
**Describe the Issue**
I find the url in the comment of these two files are invalid currently. Maybe we need to re-run the configs in the benchmark to check the availability. Or we can add some unit test or CI to check the availability of the config files in benchmark automatically.

- https://github.com/open-mmlab/mmselfsup/blob/1.x/configs/benchmarks/mmsegmentation/cityscapes/fcn_r50-d8_769x769_40k_cityscapes.py
- https://github.com/open-mmlab/mmselfsup/blob/1.x/configs/benchmarks/mmsegmentation/voc12aug/fcn_r50-d8_512x512_20k_voc12aug.py

**Comment by fangyixiao18** [comment]
PR link: https://github.com/open-mmlab/mmselfsup/pull/538
