### ISSUE TITLE
[Feature] Support Masked Image Modeling reconstruction visualization

### ISSUE THREAD

**Issue by fangyixiao18** [open-mmlab/mmselfsup#553]
### What is the problem this feature will solve?

Add scripts and functions to support visualize MIM reconstruction.

### What is the feature?

Like MAE visuzalization, support other MIM algorithms.
![image](https://user-images.githubusercontent.com/36138628/198520601-f27444ed-7d72-4ab8-93ab-31622ba11043.png)

### What alternatives have you considered?

- [x] MAE
- [x] SimMIM
- [x] MaskFeat
- [ ] ConvMAE

**Comment by tonysy** [comment]
#471
