### ISSUE TITLE
[Bug] Bug in get_started

### ISSUE THREAD

**Issue by tonysy** [open-mmlab/mmselfsup#559]
### Branch

1.x branch (1.x version, such as `v1.0.0rc2`, or `dev-1.x` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmselfsup/issues) and [Discussions](https://github.com/open-mmlab/mmselfsup/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmselfsup.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmselfsup).

### Environment

None

### Describe the bug

The script provided in get_started is invalid.

```
KeyError: 'Classification is not in the model registry. Please check whether the value of `Classification` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/tutorials/config.html#import-custom-python-modules'
```

### Additional information

From wechat user

**Comment by fangyixiao18** [comment]
Remove this part in https://github.com/open-mmlab/mmselfsup/pull/548
