### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by HUUA** [open-mmlab/mmselfsup#568]
### Branch

master branch (0.x version, such as `v0.10.0`, or `dev` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmselfsup/issues) and [Discussions](https://github.com/open-mmlab/mmselfsup/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmselfsup.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmselfsup).

### Environment

ubuntu 22.04.1
torch 1.14.0.dev20221027+cu117 pypi_0 pypi
torchaudio 0.14.0.dev20221027+cu117 pypi_0 pypi
torchvision 0.15.0.dev20221027+cu117
mmselfsup 0.10.0
cuda 11.7
nvidia driver 520.06

### Describe the bug

whenever i pass“bash tools/dist_train.sh configs/selfsup/byol/byol_resnet50_8xb32-accum16-coslr-100e_in1k.py 4”,1~2 minutes, the machine will restart。
Run 3 graphics cards, the machine no restart.

I use stress-ng. I can't connect the machine to ssh, the machine does not restart, and after the pressure test is over, it also recovers, but as long as I run this, the machine will really restart

### Reproduces the problem - command or script

bash tools/dist_train.sh configs/selfsup/byol/byol_resnet50_8xb32-accum16-coslr-100e_in1k.py 4

**Comment by tonysy** [comment]
Hi, this issue may come from the hardware issue(like memory, or power(high utilization rate to cause shutdown)), or the version of driver.

-  You may check the utilization rate of CPU,GPU,Memroy by using `free`, `htop`, `nvidia-smi` etc.
- Try previous version driver and CUDA, the 11.7 seems too new.
- Try other algorithm or reduce the batch size/num_workers.
- Try other repoes, like MMClassification, and MMDetection
