### ISSUE TITLE
[Bug] DOS format EOF in prepare_voc07_cls.sh

### ISSUE THREAD

**Issue by ryan-minato** [open-mmlab/mmselfsup#591]
### Branch

master branch (0.x version, such as `v0.10.0`, or `dev` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmselfsup/issues) and [Discussions](https://github.com/open-mmlab/mmselfsup/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmselfsup.readthedocs.io/en/latest/) but cannot get the expected help.
- [x] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmselfsup).

### Environment

A error is raised in docker and windows.

Docker image was created from this Dockerfile. ([like this](https://github.com/open-mmlab/mmselfsup/blob/dev-1.x/docker/Dockerfile))
``` Dockerfile
ARG PYTORCH="1.10.0"
ARG CUDA="11.3"
ARG CUDNN="8"

FROM pytorch/pytorch:${PYTORCH}-cuda${CUDA}-cudnn${CUDNN}-devel

ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 8.0 7.0+PTX"
ENV TORCH_NVCC_FLAGS="-Xfatbin -compress-all"
ENV CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"

RUN : \
    && apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub \
    && apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub \
    && apt-get update \
    && apt-get install -y ffmpeg libsm6 libxext6 git ninja-build libglib2.0-0 libsm6 libxrender-dev libxext6 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install MMCV MMDetection MMSegmentation
RUN pip install mmcv-full==1.3.16 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/index.html
RUN pip install mmsegmentation mmdet
# Install MMSelfSup
RUN conda clean --all
RUN git clone https://github.com/open-mmlab/mmselfsup.git  /mmselfsup
WORKDIR /mmselfsup
ENV FORCE_CUDA="1"
RUN pip install --no-cache-dir -e .
```

### Describe the bug

i have run the shell script as the tutorial '[PREPARE DATASETS](https://mmselfsup.readthedocs.io/en/latest/prepare_data.html#:~:text=bash%20tools/data_converters/prepare_voc07_cls.sh%20%24YOUR_DATA_ROOT)'
``` bash
bash tools/data_converters/prepare_voc07_cls.sh $YOUR_DATA_ROOT
```
It raised two error.
``` shell
tools/data_converters/prepare_voc07_cls.sh: line 2: $'\r': command not found
tools/data_converters/prepare_voc07_cls.sh: line 35: syntax error: unexpected end of file
```

It looks like a typically EOF format error.

### Additional information

This problem can be solved by using `dos2unix`

``` shell
dos2unix ./tools/data_converters/prepare_voc07_cls.sh
```

**Comment by YuanLiuuuuuu** [comment]
We can run this script without any problems. Could you please provide detailed information, e.g. system version, about your machine ?
