### ISSUE TITLE
Issue training SimCLR

### ISSUE THREAD

**Issue by jlindsey15** [open-mmlab/mmselfsup#6]
When I use the SimCLR training code, my code always hangs after exactly 19 epochs and 3750 iterations.  I can terminate it and restart from the previous checkpoint, but it would be nice not to have to do this.  Do you have any idea why this might happen?

**Comment by XiaohangZhan** [comment]
Are you using pytorch-1.1 & nccl-2.4.2? If so, you may refer to: https://github.com/pytorch/pytorch/issues/20630
A workaround is `export NCCL_LL_THRESHOLD=0` before training.

**Comment by jlindsey15** [comment]
Thanks, this fixed the problem!
