### ISSUE TITLE
[Docs] Applying MAE to downstream object detection

### ISSUE THREAD

**Issue by austinmw** [open-mmlab/mmselfsup#605]
### The doc issue

Hi, are there any config examples for applying MAE pretraining to the downstream task of object detection? I've trained a MAE VIT and extracted the backbone weights, but not sure how to set up a MMDetection config to use these. Maybe I can use it with Mask RCNN?

### Suggest a potential alternative/fix

I see that docs say:
```
# distributed version
bash tools/benchmarks/mmdetection/mim_dist_train.sh ${CONFIG} ${PRETRAIN} ${GPUS}
```
But it would be great if there was an example of compatible configs for MAE -> detection

**Comment by YuanLiuuuuuu** [comment]
Currently, mmdetection does not support evaluating MAE on detection task. But we will provide a converting script to transform the weights to be timm-style, then you can evaluate it with detectron2. Once the script is finished, we will reach you in this issue as soon as possible.

**Comment by austinmw** [comment]
Sounds great, thanks appreciate your response!

**Comment by YuanLiuuuuuu** [comment]
We create a [PR](https://github.com/open-mmlab/mmselfsup/pull/621) to convert the MMClassification-style weights to timm-style weights, and provide detailed instruction about how to evaluate your model on detection and segmentation. You can follow this [PR](https://github.com/open-mmlab/mmselfsup/pull/621) to have a try, and your feedback is also highly valuable!

**Comment by austinmw** [comment]
Hi, thanks for this addition! I tested it and it worked to produce a weights file for me. 

I have a question to better understand the compatibility options if you don't mind.

So the already available conversion script `extract_backbone_weights.py` seems to do:
model.pth -> backbone.pth -> train mmcls

And now the new conversion script `mmcls2tim.py` is described as:
model.pth -> timm.pth -> train detectron2

But I saw that MMDetection has a readme for timm support here: https://github.com/open-mmlab/mmdetection/blob/ca11860f4f3c3ca2ce8340e2686eeaec05b29111/configs/timm_example/README.md#timm-example

So I think I must be misunderstanding the process for one of the above, what's the technical blocker in going from timm to mmdetection with `mmcls2timm.py`?

Appreciate your help!

**Comment by YuanLiuuuuuu** [comment]
Hi, thank you for your feedbacks.

1. ``extract_backbone_weights.py`` is mainly used in MMSelfSup 0.x, which is used to extract the backbone weights and remove the ``backbone.`` prefix. In 1.x, we no longer use it. 
2. ``mmcls2timm.py`` converts the keys, specifically for ViT, from MMClassification style to timm style (but not for the reversed process), and the converted ckpt can be directly used by detectron2.
3. This [doc](https://github.com/open-mmlab/mmdetection/blob/ca11860f4f3c3ca2ce8340e2686eeaec05b29111/configs/timm_example/README.md#timm-example) in MMDetection suggests you can insert timm backbones into MMDetection. But, currently, MMDetection dose not support ViTDet. 

Hope these can be helpful to clear your confusion~

**Comment by austinmw** [comment]
Very helpful thanks!

**Comment by YuanLiuuuuuu** [comment]
Close with being solved, if you have any other problems, feel free to reopen it.
