### ISSUE TITLE
[Bug] colour distortion of the reconstructed image

### ISSUE THREAD

**Issue by IzzeddinTeeti** [open-mmlab/mmselfsup#628]
### Branch

master branch (0.x version, such as `v0.10.0`, or `dev` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmselfsup/issues) and [Discussions](https://github.com/open-mmlab/mmselfsup/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmselfsup.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmselfsup).

### Environment

sys.platform: linux
Python: 3.8.15 | packaged by conda-forge | (default, Nov 22 2022, 08:49:35) [GCC 10.4.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: Tesla V100-SXM2-32GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.7, V11.7.99
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.13.0+cu117
PyTorch compiling details: PyTorch built with:

GCC 9.3
C++ Version: 201402
Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
OpenMP 201511 (a.k.a. OpenMP 4.5)
LAPACK is enabled (usually provided by MKL)
NNPACK is enabled
CPU capability usage: AVX2
CUDA Runtime 11.7
NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
CuDNN 8.6 (built against CUDA 11.8)
Built with CuDNN 8.5
Magma 2.6.1
Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,
TorchVision: 0.14.0+cu117
OpenCV: 4.6.0
MMCV: 1.7.0
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.7
MMSelfSup: 0.10.1+85c795e

### Describe the bug

After training MAE, I got the following results, which shows a colour distortion in the reconstructed image, any clue of how to fix it?
<img width="1143" alt="Screenshot 2022-12-12 at 14 50 58" src="https://user-images.githubusercontent.com/20052288/207063061-73028f57-39f2-458f-857c-a25814a82ddd.png">

**Comment by fangyixiao18** [comment]
It is because during training of MAE, it computes the norm_pix [here](https://github.com/open-mmlab/mmselfsup/blob/master/mmselfsup/models/heads/mae_head.py#L62), in the 1.x branch, I have fixed it, you can refer to this [PR](https://github.com/open-mmlab/mmselfsup/pull/570)

**Comment by IzzeddinTeeti** [comment]
Thanks for your prompt response. I used 1.x branch to train on ImageNet tiny for 400 epoch, I run the visualisation code twice, once with `--norm-pix` and I got the following image, and once without `--norm-pix` and I got the following error. Do you know what would be the problem?
<img width="1133" alt="Screenshot 2022-12-12 at 20 00 18" src="https://user-images.githubusercontent.com/20052288/207131386-7f34a544-440c-4d5c-b612-72a263cacea8.png">

<img width="964" alt="Screenshot 2022-12-12 at 20 01 03" src="https://user-images.githubusercontent.com/20052288/207131574-931640a0-7b96-4b3f-8326-2ee7862b6ec9.png">

**Comment by fangyixiao18** [comment]
For the error, you could check the device and change it to cpu to avoid this. Here might be a potential bug, we will check it later.
As for the reconstruction, it seems that it learned some shape features but it can't reconstruct the detail. Maybe the imagenet tiny dataset is kind of small or 400 epoch is not enough.

**Comment by fangyixiao18** [comment]
The issue will be closed. If you have any other questions, feel free to open a new one.
