### ISSUE TITLE
[Bug] IterBasedRunner does not  work with distributed training

### ISSUE THREAD

**Issue by linmou** [open-mmlab/mmselfsup#638]
### Branch

master branch (0.x version, such as `v0.10.0`, or `dev` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmselfsup/issues) and [Discussions](https://github.com/open-mmlab/mmselfsup/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmselfsup.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmselfsup).

### Environment

sys.platform: linux
Python: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21) [GCC 10.3.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: A100-SXM-80GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.3, V11.3.109
GCC: gcc (Debian 8.3.0-6) 8.3.0
PyTorch: 1.10.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80
  - CuDNN 8.4.1  (built against CUDA 11.6)
    - Built with CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.1+cu113
OpenCV: 4.6.0
MMCV: 1.6.2
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.3
MMSelfSup: 0.9.2+3ac192d

### Describe the bug

When I use iter_based_runner to train a model with DDP, I find that current version seems not support iter_based_runner

Here is the bug report.
> raceback (most recent call last):                                                                                                                             File "/mnt/bd/music-lqbd32-31t-dxj/mmselfsup_new/tools/train.py", line 224, in <module>                   main()                                                                                                                                                     File "/mnt/bd/music-lqbd32-31t-dxj/mmselfsup_new/tools/train.py", line 214, in main                                                                          train_model(                                                                                                                                               File "/mnt/bd/music-lqbd32-31t-dxj/mmselfsup_new/mmselfsup/apis/train.py", line 226, in train_model       runner.run(data_loaders, cfg.workflow)                                                                                                                     File "/opt/conda/lib/python3.9/site-packages/mmcv/runner/iter_based_runner.py", line 130, in run self.call_hook('before_epoch')                                              File "/opt/conda/lib/python3.9/site-packages/mmcv/runner/base_runner.py", line 317, in call_hook    getattr(hook, fn_name)(self)                                                File "/opt/conda/lib/python3.9/site-packages/mmcv/runner/hooks/sampler_seed.py", line 15, in before_epoch if hasattr(runner.data_loader.sampler, 'set_epoch'):                        AttributeError: 'IterBasedRunner' object has no attribute 'data_loader'  

And I found the following annotation under the definition of class 'DistSamplerSeedHook', saying that

> 'When distributed training, it is only useful in conjunction with
> :obj:EpochBasedRunner, while :obj:IterBasedRunner achieves the same
> purpose with :obj:IterLoader.'
> 

It seems that simply annotating the corresponding call function makes the code run.
I annotated the line here. 
https://github.com/open-mmlab/mmselfsup/blob/1b098964e0ca9c58c0eb1fb7ba575af4c0d1e6aa/mmselfsup/apis/train.py#L162

But does it lead to further mistakes? I have no idea why we need 'DistSamplerSeedHook'

So any official guidance about using IterBasedRunner in distributed training?

**Comment by fangyixiao18** [comment]
Hello, it is a potential bug here. You may comment out the [code](https://github.com/open-mmlab/mmselfsup/blob/master/mmselfsup/apis/train.py#L162), IterBased doesn't need 'DistSamplerSeedHook', it has [IterLoader](https://github.com/open-mmlab/mmcv/blob/c47c9196d067a0900b7b8987a8e82768edab2fff/mmcv/runner/iter_based_runner.py#L19), you could refer to this [doc](https://mmcv.readthedocs.io/en/latest/understand_mmcv/runner.html)

**Comment by fangyixiao18** [comment]
You could try it as I commented above. If you have any other questions, feel free to comment here

**Comment by linmou** [comment]
Thanks a lot. It works after the line is commented. But I wonder if there is any futher potential bug owing to the commented line? For example, if I want to use ' EpochBasedRunner', is DistSamplerSeedHook necessary ?

**Comment by fangyixiao18** [comment]
> Thanks a lot. It works after the line is commented. But I wonder if there is any futher potential bug owing to the commented line? For example, if I want to use ' EpochBasedRunner', is DistSamplerSeedHook necessary ?

For `EpochBasedRunner`, DistSamplerSeedHook is needed, because it will update the epoch information in sampler, which influences the randomness behavior

**Comment by fangyixiao18** [comment]
The issue will be closed. If you have any other questions, feel free to open a new one.
