### ISSUE TITLE
InterCLR implemetation

### ISSUE THREAD

**Issue by MRJasonP** [open-mmlab/mmselfsup#64]
Hi Xiaohang,
Thank you for sharing the amazing work. 
I would like to check with you whether this repo contains the implementation&pretrianed models of InterCLR method. I read your recent paper "Delving into Inter-Image Invariance for Unsupervised Visual Representations", and would like to further study the method. 

Thank you

**Comment by XiaohangZhan** [comment]
Code of InterCLR will be released once it is accepted.
