### ISSUE TITLE
[Feature] Does mmselfsup support Fully Sharded Data Parallel (FSDP) ? 

### ISSUE THREAD

**Issue by linmou** [open-mmlab/mmselfsup#656]
### What is the problem this feature will solve?

Since some transformer structure is too huge to be loaded on a single GPU. Does mmselfsup support API  that load such big models with more than one GPUs?

### What is the feature?

An user-friendly api to load different layers of a huge model to several devices. Just like huggingface models' model.parallelize()

**Comment by fangyixiao18** [comment]
FSDP is supported in MMEngine, you can also apply it in MMSelfSup. you can try it according to the docs below
https://github.com/open-mmlab/mmengine/blob/main/docs/en/examples/save_gpu_memory.md
