### ISSUE TITLE
AttributeError: 'Clustering' object has no attribute 'obj'

### ISSUE THREAD

**Issue by datuizhuang** [open-mmlab/mmselfsup#69]
Hello，thanks for your work.
When i run the code, i met the question:
      __getattr__ = lambda self, name: _swig_getattr(self, Clustering, name)
      File "/home/anaconda3/envs/uda/lib/python3.6/site-packages/faiss/swigfaiss_avx2.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'Clustering' object has no attribute 'obj'

How to solve this Error? Thanks.

**Comment by Jiahao000** [comment]
Hi, this is due to the version incompability of faiss-gpu, please refer to [this issue](https://github.com/open-mmlab/OpenSelfSup/issues/41).

**Comment by datuizhuang** [comment]
Thanks for your answer~ I simply rewrite the code "losses = faiss.vector_to_array(clus.obj)" --> "losses = [0]" because i found it not been used,haha
