### ISSUE TITLE
AttributeError: 'MAE' object has no attribute 'reconstruct'

### ISSUE THREAD

**Issue by liusongbai98** [open-mmlab/mmselfsup#694]
### Branch

1.x branch (1.x version, such as `v1.0.0rc2`, or `dev-1.x` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmselfsup/issues) and [Discussions](https://github.com/open-mmlab/mmselfsup/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmselfsup.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmselfsup).

### Environment

python tools/analysis_tools/visualize_reconstruction.py configs/selfsup/mae/mae_vit-huge-p16_8xb512-amp-coslr-1600e_in1k.py \
    --checkpoint https://download.openmmlab.com/mmselfsup/1.x/mae/mae_vit-huge-p16_8xb512-fp16-coslr-1600e_in1k/mae_vit-huge-p16_8xb512-fp16-coslr-1600e_in1k_20220916-ff848775.pth \
    --img-path data/imagenet/val/ILSVRC2012_val_00000003.JPEG \
    --out-file test_mae.jpg \
    --norm-pix

### Describe the bug

AttributeError: 'MAE' object has no attribute 'reconstruct'

**Comment by fangyixiao18** [comment]
What is your version of mmselfsup? I tested it and I can get the output

**Comment by liusongbai98** [comment]
@fangyixiao18 1.x

**Comment by liusongbai98** [comment]
>>> print(mmselfsup.__version__)
1.0.0rc3 @fangyixiao18

**Comment by fangyixiao18** [comment]
> 1.0.0rc3 @fangyixiao18

Please update to 1.0.0rc4 at least, we refactor the visualization api in that version

**Comment by liusongbai98** [comment]
@fangyixiao18 ERROR: Could not find a version that satisfies the requirement mmselfsup>=1.0.0rc4 (from versions: 0.5.0, 0.6.0, 0.7.0, 0.7.1, 0.8.0, 0.9.0, 0.9.1, 0.9.2, 0.10.0, 0.10.1, 1.0.0rc0, 1.0.0rc1, 1.0.0rc2, 1.0.0rc3)
ERROR: No matching distribution found for mmselfsup>=1.0.0rc4
how to updata

**Comment by YuanLiuuuuuu** [comment]
Please follow steps below:

1. git checkout dev-1.x
2. git pull origin dev-1.x

Then you can have a try

**Comment by liusongbai98** [comment]
@fangyixiao18 root@autodl-container-927411beae-25963baf:~/autodl-tmp/mmselfsup# git pull origin dev-1.x
From https://github.com/open-mmlab/mmselfsup
 * branch            dev-1.x    -> FETCH_HEAD
Already up to date.

how to try .sry

**Comment by liusongbai98** [comment]
@YuanLiuuuuuu  root@autodl-container-927411beae-25963baf:~/autodl-tmp/mmselfsup# git pull origin dev-1.x
From https://github.com/open-mmlab/mmselfsup

branch dev-1.x -> FETCH_HEAD
Already up to date.
how to try .sry

**Comment by liusongbai98** [comment]
@YuanLiuuuuuu root@autodl-container-927411beae-25963baf:~/autodl-tmp/mmselfsup# git pull origin dev-1.x
From https://github.com/open-mmlab/mmselfsup
 * branch            dev-1.x    -> FETCH_HEAD
Updating 6c13b42..4591dd4
Fast-forward
 README.md | 14 ++++++++++++++
 1 file changed, 14 insertions(+)
root@autodl-container-927411beae-25963baf:~/autodl-tmp/mmselfsup# import mmselfsup
bash: import: command not found
root@autodl-container-927411beae-25963baf:~/autodl-tmp/mmselfsup# python
Python 3.8.10 (default, Jun  4 2021, 15:09:15) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mmselfsup
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/autodl-tmp/mmselfsup/mmselfsup/__init__.py", line 2, in <module>
    import mmcls
    ModuleNotFoundError: No module named 'mmcls'
    
how to solve    "   ModuleNotFoundError: No module named 'mmcls'   "

**Comment by liusongbai98** [comment]
@YuanLiuuuuuu root@autodl-container-927411beae-25963baf:~/autodl-tmp/mmselfsup# python /root/autodl-tmp/mmselfsup/tools/analysis_tools/visualize_reconstruction.py /root/autodl-tmp/mmselfsup/configs/selfsup/mae/mae_vit-huge-p16_8xb512-amp-coslr-1600e_in1k.py     --checkpoint https://download.openmmlab.com/mmselfsup/1.x/mae/mae_vit-huge-p16_8xb512-fp16-coslr-1600e_in1k/mae_vit-huge-p16_8xb512-fp16-coslr-1600e_in1k_20220916-ff848775.pth     --img-path /root/autodl-tmp/data/imagenet/val/n01440764/ILSVRC2012_val_00009111.JPEG     --out-file test_mae.jpg     --norm-pix
Traceback (most recent call last):
  File "/root/autodl-tmp/mmselfsup/tools/analysis_tools/visualize_reconstruction.py", line 13, in <module>
    from mmselfsup.apis import inference_model, init_model
ModuleNotFoundError: No module named 'mmselfsup'
