### ISSUE TITLE
maskfeat重建可视化报错

### ISSUE THREAD

**Issue by liusongbai98** [open-mmlab/mmselfsup#695]
### Branch

1.x branch (1.x version, such as `v1.0.0rc2`, or `dev-1.x` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmselfsup/issues) and [Discussions](https://github.com/open-mmlab/mmselfsup/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmselfsup.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmselfsup).

### Environment

1.0.0rc6

### Describe the bug

![b049eaec7f480924e59588c9a20d08b](https://user-images.githubusercontent.com/125562051/219562716-75dc8367-2090-4eb5-a3a1-5a10fbaeabdd.png)

用maskfeat重建可视化报错缺少属性。

**Comment by fangyixiao18** [comment]
Solved in wechat.
Need to add `--use-vis-pipeline` in command
