### ISSUE TITLE
T-SNE报错

### ISSUE THREAD

**Issue by liusongbai98** [open-mmlab/mmselfsup#696]
### Branch

1.x branch (1.x version, such as `v1.0.0rc2`, or `dev-1.x` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmselfsup/issues) and [Discussions](https://github.com/open-mmlab/mmselfsup/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmselfsup.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmselfsup).

### Environment

1.0.0rc6

### Describe the bug

![image](https://user-images.githubusercontent.com/125562051/219572268-c2124bd3-122e-448f-b8d5-335123fe701a.png)
TypeError: 'int' object is not iterable

**Comment by fangyixiao18** [comment]
please check the input of `out_indices`
