### ISSUE TITLE
About the Imagenet data preparation

### ISSUE THREAD

**Issue by fdujay** [open-mmlab/mmselfsup#7]
Thanks for your repo! It's really helpful for me.
But when I prepare ImageNet and Places205(cause my research direction was medical imaging , I'm not familiar with these),
![图片](https://user-images.githubusercontent.com/52920323/85353450-d71db380-b53a-11ea-950b-bd6ca422895a.png)
I found that your shared [url](https://drive.google.com/drive/folders/1wYkJU_1qRHEt1LPVjBiG6ddUFV-t9hVJ) was empty.
So can you provide the write url for preparing ImageNet? Thank you very much!

**Comment by XiaohangZhan** [comment]
Thank you for reminding me, I uploaded it just now.

**Comment by fdujay** [comment]
Thanks! My problem was solved.
