### ISSUE TITLE
[Bug] setup.py install is deprecated

### ISSUE THREAD

**Issue by wangzhaoyang-508** [open-mmlab/mmselfsup#705]
### Branch

1.x branch (1.x version, such as `v1.0.0rc2`, or `dev-1.x` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmselfsup/issues) and [Discussions](https://github.com/open-mmlab/mmselfsup/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmselfsup.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmselfsup).

### Environment

I use GeForce 4090*2
CUDA=11.6  CUDNN =8.7.0
torch.version==1.13.1+cu116
torchvision==0.14.1+cu116
cuda.isavailable = True

I use “conda install pytorch torchvision -c pytorch” in [official instructions] but cuda.isavailable = False，so i use pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116  
to install torch.

but when i run setup.py ,warning occurs :

reading manifest file '/tmp/pip-pip-egg-info-j9smn123/mmselfsup.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'mmselfsup/VERSION'
  warning: no files found matching 'mmselfsup/.mim/model-index.yml'
  warning: no files found matching '*.py' under directory 'mmselfsup/.mim/configs'
  warning: no files found matching '*.yml' under directory 'mmselfsup/.mim/configs'
  warning: no files found matching '*.sh' under directory 'mmselfsup/.mim/tools'
  warning: no files found matching '*.py' under directory 'mmselfsup/.mim/tools'
  adding license file 'LICENSE'
  writing manifest file '/tmp/pip-pip-egg-info-j9smn123/mmselfsup.egg-info/SOURCES.txt'
  Preparing metadata (setup.py) ... done

so i can not import mmselfsup 

### Describe the bug

I use “conda install pytorch torchvision -c pytorch” in [official instructions] but cuda.isavailable = False，so i use pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116  
to install torch.

but when i run setup.py ,warning occurs :

 log:
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'mmselfsup/VERSION'
  warning: no files found matching 'mmselfsup/.mim/model-index.yml'
  warning: no files found matching '*.py' under directory 'mmselfsup/.mim/configs'
  warning: no files found matching '*.yml' under directory 'mmselfsup/.mim/configs'
  warning: no files found matching '*.sh' under directory 'mmselfsup/.mim/tools'
  warning: no files found matching '*.py' under directory 'mmselfsup/.mim/tools'
  adding license file 'LICENSE'
  writing manifest file '/tmp/pip-pip-egg-info-j9smn123/mmselfsup.egg-info/SOURCES.txt'
  Preparing metadata (setup.py) ... done

/anaconda3/envs/mmselfsup/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    warning: no files found matching 'mmselfsup/VERSION'
    adding license file 'LICENSE'
    writing manifest file 'mmselfsup.egg-info/SOURCES.txt'
    running build_ext
    Creating /anaconda3/envs/mmselfsup/lib/python3.8/site-packages/mmselfsup.egg-link (link to .)
    Adding mmselfsup 1.0.0rc6 to easy-install.pth file

so i can not import mmselfsup

### Reproduces the problem - code sample

git clone https://github.com/open-mmlab/mmselfsup.git
cd mmselfsup
pip install -v -e .
# "-v" means verbose, or more output
# "-e" means installing a project in editable mode,
# thus any local modifications made to the code will take effect without reinstallation.

### Reproduces the problem - error message

 log:
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'mmselfsup/VERSION'
  warning: no files found matching 'mmselfsup/.mim/model-index.yml'
  warning: no files found matching '*.py' under directory 'mmselfsup/.mim/configs'
  warning: no files found matching '*.yml' under directory 'mmselfsup/.mim/configs'
  warning: no files found matching '*.sh' under directory 'mmselfsup/.mim/tools'
  warning: no files found matching '*.py' under directory 'mmselfsup/.mim/tools'
  adding license file 'LICENSE'
  writing manifest file '/tmp/pip-pip-egg-info-j9smn123/mmselfsup.egg-info/SOURCES.txt'
  Preparing metadata (setup.py) ... done

/anaconda3/envs/mmselfsup/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    warning: no files found matching 'mmselfsup/VERSION'
    adding license file 'LICENSE'
    writing manifest file 'mmselfsup.egg-info/SOURCES.txt'
    running build_ext
    Creating /anaconda3/envs/mmselfsup/lib/python3.8/site-packages/mmselfsup.egg-link (link to .)
    Adding mmselfsup 1.0.0rc6 to easy-install.pth file

so i can not import mmselfsup

**Comment by wangbo-zhao** [comment]
Can u show all logs?

**Comment by wangzhaoyang-508** [comment]
> 



> Can u show all logs?

I delete the env and recreated a new one,
via enter "mim install -U openmim/ mim install mmengine/ mim install‘mmcv>=2.0.0rc1’/" 
I can import mmsulfsup successfully for now, but the warning still exist when i run setup.py。does it matter？

**Comment by wangbo-zhao** [comment]
From your log, I can only find warrnings but no errors. I think warnings do not matter. I think it would be better to recreate a new environment when u start to do a new project. This helps u avoid some strange problems.

**Comment by wangzhaoyang-508** [comment]
> From your log, I can only find warrnings but no errors. I think warnings do not matter. I think it would be better to recreate a new environment when u start to do a new project. This helps u avoid some strange problems.

I see ,thanks.
