### ISSUE TITLE
About the predictor of BYOL

### ISSUE THREAD

**Issue by YuqingWang1029** [open-mmlab/mmselfsup#71]
It seems that the online and target network architecture is the same, where is the predictor network of online , have I miss something? https://github.com/open-mmlab/OpenSelfSup/blob/ed5000482b0d8b816cd8a6fbbb1f97da44916fed/openselfsup/models/byol.py#L35

**Comment by XiaohangZhan** [comment]
The predictor is in the head.

**Comment by YuqingWang1029** [comment]
OK, thanks for you quick reply.
