### ISSUE TITLE
[Bug] Issues in Visualize Shape Bias 

### ISSUE THREAD

**Issue by guneetmutreja** [open-mmlab/mmselfsup#716]
### Branch

1.x branch (1.x version, such as `v1.0.0rc2`, or `dev-1.x` branch)

### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmselfsup/issues) and [Discussions](https://github.com/open-mmlab/mmselfsup/discussions) but cannot get the expected help.
- [X] I have read the [documentation](https://mmselfsup.readthedocs.io/en/latest/) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmselfsup).

### Environment

sys.platform: linux
Python: 3.8.16 (default, Jan 17 2023, 23:13:24) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA TITAN RTX
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.0, V11.0.194
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.8.2
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.9.2
OpenCV: 4.7.0
MMEngine: 0.6.0
MMCV: 2.0.0rc4
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMSelfSup: 1.0.0rc6+

### Describe the bug

```shell
GPUS=1 bash tools/benchmarks/classification/mim_dist_test.sh configs/selfsup/simclr/simclr_resnet50_8xb32-coslr-200e_Custom_cue.py working_dir/simclr/Custom/epoch_200.pth
```

This command throws the following error:
test.py: error: argument --cfg-options: expected at least one argument

# Edited config file:
 
_base_ = [
    '../_base_/models/simclr.py',
    '../_base_/schedules/lars_coslr-200e_in1k.py',
    '../_base_/default_runtime.py',
]

dataset_type = 'mmcls.CustomDataset'
data_root = 'data/Custom/'
file_client_args = dict(backend='disk')

view_pipeline = [
    dict(type='RandomResizedCrop', size=224, backend='pillow'),
    dict(type='RandomFlip', prob=0.5),
    dict(
        type='RandomApply',
        transforms=[
            dict(
                type='ColorJitter',
                brightness=0.8,
                contrast=0.8,
                saturation=0.8,
                hue=0.2)
        ],
        prob=0.8),
    dict(
        type='RandomGrayscale',
        prob=0.2,
        keep_channels=True,
        channel_weights=(0.114, 0.587, 0.2989)),
    dict(type='RandomGaussianBlur', sigma_min=0.1, sigma_max=2.0, prob=0.5),
]

train_pipeline = [
    dict(type='LoadImageFromFile', file_client_args=file_client_args),
    dict(type='MultiView', num_views=2, transforms=[view_pipeline]),
    dict(type='PackSelfSupInputs', meta_keys=['img_path'])
]

train_dataloader = dict(
    batch_size=32,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    collate_fn=dict(type='default_collate'),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        ann_file='meta/train.txt',
        data_prefix=dict(img_path='train/1/'),
        pipeline=train_pipeline))
        
test_dataloader = dict(
    dataset=dict(
        type='CustomDataset',
        data_root='data/cue-conflict',
        _delete_=True),
    drop_last=False)
test_evaluator = dict(
    type='mmselfsup.ShapeBiasMetric',
    _delete_=True,
    csv_dir='csv',
    model_name='simclr')
             
optimizer = dict(type='LARS', lr=0.3, momentum=0.9, weight_decay=1e-6)
optim_wrapper = dict(
    type='OptimWrapper',
    optimizer=optimizer,
    paramwise_cfg=dict(
        custom_keys={
            'bn': dict(decay_mult=0, lars_exclude=True),
            'bias': dict(decay_mult=0, lars_exclude=True),
            # bn layer in ResNet block downsample module
            'downsample.1': dict(decay_mult=0, lars_exclude=True),
        }))

default_hooks = dict(
    # only keeps the latest 3 checkpoints
    checkpoint=dict(type='CheckpointHook', interval=10, max_keep_ckpts=3))

### Reproduces the problem - command or script

```shell

GPUS=1 bash tools/benchmarks/classification/mim_dist_test.sh configs/selfsup/simclr/simclr_resnet50_8xb32-coslr-200e_Custom_cue.py working_dir/simclr/Custom/epoch_200.pth
```

## Traceback
```
+ CFG=configs/selfsup/simclr/simclr_resnet50_8xb32-coslr-200e_Custom_cue.py
+ CHECKPOINT=working_dir/simclr/Custom/epoch_200.pth
+ GPUS=1
+ PY_ARGS=
++ dirname tools/benchmarks/classification/mim_dist_test.sh
+ PYTHONPATH=tools/benchmarks/classification/..:/home/xdibias/xdibias2-Ubuntu-20.04/current/lib/python:/home/xdibias/xdibias2-Ubuntu-20.04/2023-02-10T16-46-55+01-00-cc954c13/lib/python:
+ mim test mmcls configs/selfsup/simclr/simclr_resnet50_8xb32-coslr-200e_Custom_cue.py --checkpoint working_dir/simclr/Custom/epoch_200.pth --launcher pytorch -G 1 --cfg-options
Using port 27500 for synchronization. 
Testing command is /home/mutr_gu/anaconda3/envs/arcgis_mmselfsup/bin/python -m torch.distributed.launch --nproc_per_node=1 --master_port=27500 /home/mutr_gu/anaconda3/envs/arcgis_mmselfsup/lib/python3.8/site-packages/mmcls/.mim/tools/test.py configs/selfsup/simclr/simclr_resnet50_8xb32-coslr-200e_Custom_cue.py working_dir/simclr/Custom/epoch_200.pth --launcher pytorch --cfg-options. 
usage: test.py [-h] [--work-dir WORK_DIR] [--out OUT] [--dump DUMP]
               [--cfg-options CFG_OPTIONS [CFG_OPTIONS ...]]
               [--show-dir SHOW_DIR] [--show] [--interval INTERVAL]
               [--wait-time WAIT_TIME] [--no-pin-memory] [--tta]
               [--launcher {none,pytorch,slurm,mpi}] [--local_rank LOCAL_RANK]
               config checkpoint
test.py: error: argument --cfg-options: expected at least one argument
Killing subprocess 1079418
Traceback (most recent call last):
  File "/home/mutr_gu/anaconda3/envs/arcgis_mmselfsup/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/mutr_gu/anaconda3/envs/arcgis_mmselfsup/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/mutr_gu/anaconda3/envs/arcgis_mmselfsup/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/mutr_gu/anaconda3/envs/arcgis_mmselfsup/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/mutr_gu/anaconda3/envs/arcgis_mmselfsup/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/mutr_gu/anaconda3/envs/arcgis_mmselfsup/bin/python', '-u', '/home/mutr_gu/anaconda3/envs/arcgis_mmselfsup/lib/python3.8/site-packages/mmcls/.mim/tools/test.py', '--local_rank=0', 'configs/selfsup/simclr/simclr_resnet50_8xb32-coslr-200e_Custom_cue.py', 'working_dir/simclr/Custom/epoch_200.pth', '--launcher', 'pytorch', '--cfg-options']' returned non-zero exit status 2.
Traceback (most recent call last):
  File "/home/mutr_gu/anaconda3/envs/arcgis_mmselfsup/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "/home/mutr_gu/anaconda3/envs/arcgis_mmselfsup/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/mutr_gu/anaconda3/envs/arcgis_mmselfsup/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/mutr_gu/anaconda3/envs/arcgis_mmselfsup/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mutr_gu/anaconda3/envs/arcgis_mmselfsup/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mutr_gu/anaconda3/envs/arcgis_mmselfsup/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/mutr_gu/anaconda3/envs/arcgis_mmselfsup/lib/python3.8/site-packages/mim/commands/test.py", line 109, in cli
    is_success, msg = test(
  File "/home/mutr_gu/anaconda3/envs/arcgis_mmselfsup/lib/python3.8/site-packages/mim/commands/test.py", line 288, in test
    ret = subprocess.check_call(
  File "/home/mutr_gu/anaconda3/envs/arcgis_mmselfsup/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/mutr_gu/anaconda3/envs/arcgis_mmselfsup/bin/python', '-m', 'torch.distributed.launch', '--nproc_per_node=1', '--master_port=27500', '/home/mutr_gu/anaconda3/envs/arcgis_mmselfsup/lib/python3.8/site-packages/mmcls/.mim/tools/test.py', 'configs/selfsup/simclr/simclr_resnet50_8xb32-coslr-200e_Custom_cue.py', 'working_dir/simclr/Custom/epoch_200.pth', '--launcher', 'pytorch', '--cfg-options']' returned non-zero exit status 1.

```

**Comment by YuanLiuuuuuu** [comment]
Thank you for reporting this bug. We fix it in this [PR](https://github.com/open-mmlab/mmselfsup/pull/717)

**Comment by guneetmutreja** [comment]
PR merged, hence closing the issue.
