### ISSUE TITLE
Standard of shared region

### ISSUE THREAD

**Issue by sunwoo76** [open-mmlab/mmselfsup#72]
This is what I wanted!
And, I have a question.

Your figure about relations among Unsupervised Learning, Self-Supervised Learning and Representation Learning impressively.

but, What is the reason that de-occlusion and correspondence are not included in the shared region? 

Process of de-occlusion predicts the occluded region and process using correspondence should understand sincere relations between corresponding pixel or patch.
Through this, I think the representation could be learned.

thank you.

**Comment by XiaohangZhan** [comment]
Deocclusion and correspondence do not aim at learning image representations.
