### ISSUE TITLE
文档缺乏”如何构建自定义数据集“

### ISSUE THREAD

**Issue by bobo0810** [open-mmlab/mmselfsup#733]
提问： 因为自监督 不需要类别信息，只与本身相关。那么 把所有图片放在同一个文件夹里，类别序号命名为0。这样训练是否可行？
![image](https://user-images.githubusercontent.com/26057879/228713440-8733aa06-7603-4d4f-8f95-72fa9d0b8b89.png)

文档里没有写  自定义数据集的目录结构，导致理解含糊不清
![image](https://user-images.githubusercontent.com/26057879/228713501-455b79c0-49c5-4450-a9ed-404f8d39d3af.png)

**Comment by fangyixiao18** [comment]
可以的

**Comment by bobo0810** [comment]
已解决~    除了api接口，期望在用户指南里添加"自定义数据集"

![image](https://user-images.githubusercontent.com/26057879/229676017-39b22e3e-e6a9-4762-868e-caa29a6a0fc5.png)
