### ISSUE TITLE
Installation of MMCv

### ISSUE THREAD

**Issue by kalikhademi** [open-mmlab/mmselfsup#737]
Hi, 

I have followed the steps in your documentation at this link:https://mmselfsup.readthedocs.io/en/dev-1.x/get_started.html

I used command mim install 'mmcv>=2.0.0rc1' to install mmcv and it installs mmcv 2.0.0 correctly. When I wanted to import mmselfsup in the python script, it gives me the following error:

Running check script on a single CPU core
Traceback (most recent call last):
  File "/blue/second_study_codebase/mmselfsup/check.py", line 1, in <module>
    import mmselfsup
  File "/blue/second_study_codebase/mmselfsup/mmselfsup/__init__.py", line 2, in <module>
    import mmcls
  File "home/selfsup/lib/python3.9/site-packages/mmcls/__init__.py", line 17, in <module>
    assert (mmcv_version >= digit_version(mmcv_minimum_version)
AssertionError: MMCV==2.0.0 is used but incompatible. Please install mmcv>=2.0.0rc1, <2.0.0.

I also tried to install the mmcv-full but it could not be compiled. I also tried to install packages through requirements.txt in the repo and it still installs version 2.0.0. I appreciate it if you could help me as I am new on this!

Thanks, 
Kiana

**Comment by fangyixiao18** [comment]
sorry for the inconvenience, please use command `mim install 'mmcv==2.0.0rc4'` to install mmcv
