### ISSUE TITLE
Right way to reproduce results on ImageNet linear classification

### ISSUE THREAD

**Issue by deeptimhe** [open-mmlab/mmselfsup#75]
Hi,

Thanks the authors contribution to this great repo.
I am reproducing the results on ImageNet linear classification with:
1. pretrained model: moco_r50_v2-e3b0c442.pth (downloaded from model zoo)
2. config file: configs/benchmarks/linear_classification/imagenet/r50_last.py

I use 4 GPUs and accordingly adjust imgs_per_gpu=64.
The training script is:
bash benchmarks/dist_train_linear.sh configs/benchmarks/linear_classification/imagenet/r50_last.py moco_r50_v2-e3b0c442.pth

I only obtain the following performance:
head0_top1: 37.9560, head0_top5: 67.7320
While the reported performance is 67.69 on Top-1.

Is there any mistakes for the reproduction?

**Comment by Jiahao000** [comment]
Did you set GPUS=4 in dist_train_linear.sh?

**Comment by deeptimhe** [comment]
> Did you set GPUS=4 in dist_train_linear.sh?

@Jiahao000 
Yes, I set GPUS=4 in dist_train_linear.sh
And even if running with default setting (i.e., GPUs=8, imgs_per_gpu=64), it brings a comparable performance, which is significant lower than 67.69.

**Comment by Jiahao000** [comment]
Did you pull the latest version? Apart from GPUS=4 and imgs_per_gpu=64, did you change other settings?

**Comment by deeptimhe** [comment]
> Did you pull the latest version? Apart from GPUS=4 and imgs_per_gpu=64, did you change other settings?

@Jiahao000 
I carried out on the latest version. I do not modified any other setting. Could you share your training log thus I can compared it with mine.

**Comment by deeptimhe** [comment]
@Jiahao000 
It seems something wrong with the ImageNet classification evaluation codes. Since I can essentially achieve reasonable numbers with:
1. main_lincls.py (https://github.com/facebookresearch/moco)
2. pretrained parameters by tools/dist_train.sh (this repo)

**Comment by Jiahao000** [comment]
It may be due to the recent update of prefetching data. Previous version has no problem. Let me rerun the experiment to see if this casues something wrong here.

**Comment by deeptimhe** [comment]
I figured it out.
prefetch should be set to False.

**Comment by Jiahao000** [comment]
Great, good to hear that.

**Comment by XiaohangZhan** [comment]
> I figured it out.
> prefetch should be set to False.

Fixed. Please pull the latest version. Now you can use prefetch in linear classification.

**Comment by deeptimhe** [comment]
bug fixed
