### ISSUE TITLE
Default Setting of # of nodes & GPUs

### ISSUE THREAD

**Issue by Divadi** [open-mmlab/mmselfsup#753]
What is the default # of nodes & # of GPUs per node for training? I believed it to be 8 nodes, each 8 GPUs but, I just wanted to double check since "8x512" led me to believe it was perhaps 8 GPUs with 512 batch size each.

I apologize if this has been answered elsewhere.

**Comment by fangyixiao18** [comment]
> What is the default # of nodes & # of GPUs per node for training? I believed it to be 8 nodes, each 8 GPUs but, I just wanted to double check since "8x512" led me to believe it was perhaps 8 GPUs with 512 batch size each.
> 
> I apologize if this has been answered elsewhere.

Yes, the total batch size is 8 x 512 = 4096

**Comment by Divadi** [comment]
Thank you!
