### ISSUE TITLE
MMCls is called MMPreTrain now, should change the "mmcls>xxxx" in requirements to "mmpretrain>xxxx"?

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmselfsup#754]
requirements/mminstall.txt & requirements/runtime.txt

**Comment by zhongqiu1245** [comment]
Any news?

**Comment by wangbo-zhao** [comment]
Sorry for replying late. Now both mmcls and mmselfsup are moved into mmpretrain. You can use mmpretrain directly.

**Comment by zhongqiu1245** [comment]
thx
