### ISSUE TITLE
About performance of byol

### ISSUE THREAD

**Issue by jianlong-yuan** [open-mmlab/mmselfsup#77]
![image](https://user-images.githubusercontent.com/18137551/102462709-1d387780-4085-11eb-828d-57b71efb3442.png)

According to the above table, the results of byol are not fully reproduced. Do you have a duplicate result?

**Comment by XiaohangZhan** [comment]
BYOL in openselfsup is trained for 300 epoch. Though this table did not show 300 epoch, our result (72.35) is reasonable, I think.

**Comment by jianlong-yuan** [comment]
![image](https://user-images.githubusercontent.com/18137551/102569354-4a863380-4120-11eb-846c-42fbff10492a.png)

I think this is more meaningful. The same epoch and batch size.

**Comment by XiaohangZhan** [comment]
byol paper reported results with 300 epochs.
