### ISSUE TITLE
SimCRL v2

### ISSUE THREAD

**Issue by yinjunbo** [open-mmlab/mmselfsup#8]
Hi, thanks for your excellent work! 
Is there a plan to add the SimCRL v2 to this framework?

**Comment by XiaohangZhan** [comment]
Yes, it's easy to add SimCLR v2 to this framework. However, due to the limitation of computational resources, we may not be able to reproduce the results with larger backbones and large batch size. We will implement it soon.

**Comment by yinjunbo** [comment]
Looking forward to seeing the code. Thanks.

**Comment by cliangyu** [comment]
SimCLR v2 is quite needed for semi-supervised scenarios. May I know if you can release the code soon? Even if not tested. Looking forward to the code, thanks!
