### ISSUE TITLE
how to save top k model

### ISSUE THREAD

**Issue by Dangdd** [open-mmlab/mmselfsup#86]
how to save top k model?
I only find this : checkpoint_config = dict(interval=10)
but I chenge to checkpoint_config = dict(save_top_k=5)，get error

**Comment by XiaohangZhan** [comment]
What is save_top_k? It is an undefined key...

**Comment by Dangdd** [comment]
> What is save_top_k? It is an undefined key...

for example:

**Comment by Dangdd** [comment]
> What is save_top_k? It is an undefined key...

for example: 
in configs/selfsup/simclr/r50_bs256_ep200.py
save model config is checkpoint_config = dict(interval=10)

**Comment by Dangdd** [comment]
> What is save_top_k? It is an undefined key...

for example:
in configs/selfsup/simclr/r50_bs256_ep200.py
save model config is checkpoint_config = dict(interval=10)，means save model when epoch is 10,20,30...
but I want save 5 best models ,when val loss is minimum. I don't know if current version support the function,it support,how should I write config?

**Comment by Dangdd** [comment]
> What is save_top_k? It is an undefined key...

for example:
in configs/selfsup/simclr/r50_bs256_ep200.py
save model config is checkpoint_config = dict(interval=10)，means save model when epoch is 10,20,30...
but I want to save 1 best models ,when val loss is minimum. I don't know if current version support the function,if does.How to write the config file?

**Comment by XiaohangZhan** [comment]
Sorry it is not supported for now. Maybe it is easy to find the best checkpoint via parsing the log.
