### ISSUE TITLE
SimCLRv2?

### ISSUE THREAD

**Issue by jizongFox** [open-mmlab/mmselfsup#87]
Hello, 
Do you have implemented SimCLRv2 as the baseline in this repo?
Best regards,
Jizong

**Comment by XiaohangZhan** [comment]
Not yet. We will be grateful if you would like to implement it and contribute to this repo.

**Comment by jizongFox** [comment]
Hi @XiaohangZhan 
Maybe I can prepare and submit a PR if I had time.

**Comment by XiaohangZhan** [comment]
Thank you
