### ISSUE TITLE
No module named 'openselfsup'

### ISSUE THREAD

**Issue by zhoufengfan** [open-mmlab/mmselfsup#95]
After I run the command below:
`bash tools/dist_train.sh configs/selfsup/odc/r50_v1.py 4`

It get the error below:
`Traceback (most recent call last):
  File "tools/train.py", line 13, in <module>
    from openselfsup import __version__
ModuleNotFoundError: No module named 'openselfsup'
Traceback (most recent call last):
  File "tools/train.py", line 13, in <module>
    from openselfsup import __version__
ModuleNotFoundError: No module named 'openselfsup'`

How to solve it?

Thanks.

**Comment by XiaohangZhan** [comment]
Did you correctly install openselfsup following: https://github.com/open-mmlab/OpenSelfSup/blob/master/docs/INSTALL.md

**Comment by zhoufengfan** [comment]
I have run the command below:
```  bash
conda install faiss-gpu
pip install -v -e .
```
It seems like other package I have already installed through the version is different(I run the code in docker whose images is Ubuntu20.04, and my Python version is 3.8).

When I use python command interaction interface.
It can Import openselfsup, but in bash, it can't.
```
>>> import openselfsup
>>>
```

**Comment by Jiahao000** [comment]
Please correctly reinstall openselfsup following: https://github.com/open-mmlab/OpenSelfSup/blob/master/docs/INSTALL.md
