### ISSUE TITLE
Accessing Pretrained Model Weights

### ISSUE THREAD

**Issue by ColinConwell** [open-mmlab/mmselfsup#96]
Thanks for this phenomenal codebase, OpenSelfSup Team.

One small issue and a minor feature request:

It seems the weights for models like selfsup/byol/r50_bs256_accumulate16_ep300.py, for example, are inaccessible for download (Google Drive restriction, I think). Can these be made available?

Also, I'm wondering if you might be able to provide a minimally working example for the quick building and loading of the weights of a pretrained model with a similar workflow to something like PyTorch Lightning? 

Thanks in advance!

**Comment by ColinConwell** [comment]
Also, a second feature minor feature request:

Would you mind sharing the command for running linear classification on the base supervised resnet50 architecture from the associated weights file (imagenet_r50-21352794.pth)?

Thanks again!

**Comment by Jiahao000** [comment]
1. The model now is directly accessible for download.
2. Thanks for you suggestion. We do not support PyTorch Lightning currently, would appreciate it if you would like to contribute to this.
