### ISSUE TITLE
How to determine the corresponding original image items in cluster_epoch_xx.npy file

### ISSUE THREAD

**Issue by XG293** [open-mmlab/mmselfsup#97]
Thanks for your work and codes!
I am trying ODC and after I trained 440 epochs on my own dataset, I want to check how well the clusters are learned. I found there are some cluster_epoch_xx.npy files saved in work_dirs and I printed them out and obtained the cluster labels. But I am not sure what's the order of them. Are they in the order of the txt file for data loading?

**Comment by Jiahao000** [comment]
Yes, they're in the order of data loading.
