### ISSUE TITLE
A question about ODC’s Samples Memory implementation details 

### ISSUE THREAD

**Issue by ZLiu21** [open-mmlab/mmselfsup#98]
Code link:
https://github.com/open-mmlab/OpenSelfSup/blob/master/openselfsup/models/memories/odc_memory.py

On the 106th line, why is the method self._gather executed？According to my understanding of method self._gather, the return value of ind is an array whose values are all 1. In this case, self.label_bank is rarely updated (Specifically, you can see the 126th line of code)

**Comment by XiaohangZhan** [comment]
The `ind_gathered ` is just initialized as all 1, but after line 95 `dist.all_gather(ind_gathered, ind)`, the `ind_gathered ` gathers all `ind`.
